Correcting link
MicrosoftDocs/OfficeDocs-Exchange pull request #2205
Opened 2020-08-24 19:47 UTC by get-itips

2020-08-25 03:31 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-08-25 06:43 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains.md
> +    - **Exchange Online Protection**: [Manage Mail Users in EOP](https://docs.microsoft.com/microsoft-365/security/office-365-security/manage-mail-users-in-eop)
```suggestion
    - **Exchange Online Protection**: [Manage mail users in EOP](https://docs.microsoft.com/microsoft-365/security/office-365-security/manage-mail-users-in-eop)
```

2020-08-25 06:44 UTC, JohanFreelancer9 requested changes
Copy review - some additional minor edits for consistency, please.

2020-08-25 15:00 UTC, JohanFreelancer9 approved these changes

2020-08-31 20:14 UTC, scanum commented
@msdmaguire PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-08-31 21:04 UTC, merged