draft-modern-exchange-admin-center
MicrosoftDocs/OfficeDocs-Exchange pull request #2213
Opened 2020-08-26 10:41 UTC by Benny-54

The updates are as per Task 4393085. Two images are yet to be added, kindly don't review and merge it. Thank you.

2020-08-27 16:19 UTC, Benny-54 commented
@AshaIyengar21 please review this. I have updated the second article. Thank you.

2020-08-31 20:15 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-01 04:13 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +## Get to the New Exchange admin center
```suggestion
## Get to the new Exchange admin center 
```

2020-09-01 04:17 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +You must have [Microsoft 365 admin permissions](https://docs.microsoft.com/microsoft-365/admin/add-users/assign-admin-roles) to access the New Exchange admin center. For more information, see [Permis
```suggestion
You must have [Microsoft 365 admin permissions](https://docs.microsoft.com/microsoft-365/admin/add-users/assign-admin-roles) to access the new Exchange admin center. For more information, see [Permissions in Exchange Online](permissions-exo/permissions-exo.md).
```

2020-09-01 04:26 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +1. [Sign in](https://support.microsoft.com/office/e9eb7d51-5430-4929-91ab-6157c5a050b4) to Microsoft 365 or Office 365 using your work or school account (AI - Further down for the URL.we are stating
```suggestion
1. [Sign in to Microsoft 365 or Office 365](https://support.microsoft.com/office/e9eb7d51-5430-4929-91ab-6157c5a050b4) using your work or school account, and then choose the **Admin** tile.
```

2020-09-01 04:27 UTC, Benny-54 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +You must have [Microsoft 365 admin permissions](https://docs.microsoft.com/microsoft-365/admin/add-users/assign-admin-roles) to access the New Exchange admin center. For more information, see [Permis
Hi Johan, the new version will be called "New Exchange Control Center". So I can't change it to "new". Thank you for the review. Currently its in review with the internal team too. So please don't merge it yet.

2020-09-01 04:30 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +You can also get to the New Exchange admin center directly by using the URL [https://admin.exchange.microsoft.com](https://admin.exchange.microsoft.com) and signing in with your  credentials.
```suggestion
You can also get to the new Exchange admin center directly and sign in with your credentials [here](https://admin.exchange.microsoft.com).
```

2020-09-01 04:37 UTC, JohanFreelancer9 commented
@scanum Hi Manuela. These changes are not ready for a copy edit. There are many questions raised in the draft which need to be resolved first.

2020-09-01 04:40 UTC, Benny-54 commented
Please don't review and merge it yet. Its in internal review with the team. Thank you.

2020-09-01 04:43 UTC, JohanFreelancer9 commented
@Benny-54  Hi Benny. Thanks for the info and noted your comments about "New Exchange Control Center". I'll wait until internal review is complete.

2020-09-02 08:46 UTC, Benny-54 commented
@JohanFreelancer9 Hi Johan, thank you for your patience. The internal review is completed. Please go ahead with the copy editing this PR. Thank you!

2020-09-02 14:29 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +You can also get to the New Exchange admin center directly by using the URL [https://admin.exchange.microsoft.com](https://admin.exchange.microsoft.com) and sign in using your  credentials.
```suggestion
You can also get to the New Exchange admin center directly by using the URL [https://admin.exchange.microsoft.com](https://admin.exchange.microsoft.com) and signing in using your credentials.
```

2020-09-02 14:30 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +>Be sure to use a private browsing session (not a regular session) to access the Exchange admin center using the direct URL. This will prevent the credential that you are currently logged on with fro
```suggestion
> Be sure to use a private browsing session (not a regular session) to access the Exchange admin center using the direct URL. This will prevent the credential that you are currently logged on with from being used. To open an InPrivate Browsing session in Microsoft Edge or an incognito window in Google Chrome, press CTRL+SHIFT+N. To open an InPrivate Browsing session in Microsoft Edge Legacy, Internet Explorer, or a Private Browsing session in Mozilla Firefox, press CTRL+SHIFT+P.
```

2020-09-02 14:32 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +|**Insights**|Use the recommendations to discover trends and/or insights,  and take actions to fix issues related to mailbox and mail flow.|
```suggestion
|**Insights**|Use the recommendations to discover trends and/or insights, and take actions to fix issues related to mailbox and mail flow.|
```

2020-09-02 14:35 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +When you select a tab, in most cases you'll see a list view. The list view in New Exchange admin center is designed to remove limitations that existed in Exchange Control Panel in the Classic Exchang
```suggestion
When you select a tab, in most cases you'll see a list view. The list view in the New Exchange admin center is designed to remove limitations that existed in Exchange Control Panel in the Classic Exchange admin center.
```

2020-09-02 14:37 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +The Centers tile allows you to change from one admin center to another. The Me tile allows you to sign out of the EAC and sign in as a different user. The Help bubble displays contextual help for fie
```suggestion
The Centers tile allows you to change from one admin center to another. The Me tile allows you to sign out of the New Exchange admin center and sign in as a different user. The Help bubble displays contextual help for fields when you create or edit an object.
```

2020-09-02 14:42 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/exchange-admin-center.md
> +When you select a tab, in most cases you'll see a list view. The list view in Classic Exchange admin center is designed to remove limitations that existed in Exchange Control Panel.
```suggestion
When you select a tab, in most cases you'll see a list view. The list view in the Classic Exchange admin center is designed to remove limitations that existed in Exchange Control Panel.
```

2020-09-02 14:47 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2020-09-02 15:23 UTC, Benny-54 commented
@JohanFreelancer9 Hi Johan, I have made the changes. Thank you.

2020-09-02 16:11 UTC, JohanFreelancer9 approved these changes

2020-09-02 16:12 UTC, JohanFreelancer9 commented
@Benny-54 Thank you. Looks good.

2020-09-03 23:51 UTC, scanum commented
@msdmaguire PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-04 03:47 UTC, Benny-54 commented
@scanum @msdmaguire Please don't merge it yet. There was a new update request yesterday from PM. Thank you!

2020-10-07 07:41 UTC, closed without merging