Improving Step 8
MicrosoftDocs/OfficeDocs-Exchange pull request #2219
Opened 2020-08-31 22:55 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2216

To conform with current steps https://support.google.com/a/answer/7378726

2020-09-03 23:52 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-04 03:14 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md
> +8. If you see an area that says **Show Domain-Wide Delegation**, click to expand that section. Then, click the Edit button at the top of the screen and then enable the checkbox for **Enable G Suite D
```suggestion
8. If you see an area that says **Show Domain-Wide Delegation**, click to expand that section. Click the **Edit** button at the top of the screen and enable the checkbox to **Enable G Suite Domain-wide Delegation**, and then click **Save** at the bottom of the page.
```

2020-09-04 03:16 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-04 15:17 UTC, JohanFreelancer9 approved these changes

2020-09-08 04:22 UTC, scanum commented
@msdmaguire PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-08 16:41 UTC, merged