Create Disable or enable journaling of voice mail and missed call not…
MicrosoftDocs/OfficeDocs-Exchange pull request #2240
Opened 2020-09-09 17:16 UTC by Tangela123

…ifications

2020-09-09 17:24 UTC, cabailey commented
@JohanFreelancer9 This is to recreate https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2197 that got mistakenly closed & couldn't be reopened.  Please help to see this through and merge so it can be published.

2020-09-09 23:42 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/journaling/Disable or enable journaling of voice mail and missed call notifications
> +> When voice mail journaling is disabled all Unified Messages, which contain the following messages classes will not be journaled. It is important to be aware that messages that are “spoof” using the
```suggestion
> When voice mail journaling is disabled, all Unified Messages that contain the following message classes will not be journaled. It is important to be aware that messages that are “spoof” will not be journaled when using these message classes.
```

2020-09-09 23:45 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/journaling/Disable or enable journaling of voice mail and missed call notifications
> +You can only use the PowerShell to perform this procedure.
```suggestion
You can only use PowerShell to perform this procedure.
```

2020-09-09 23:45 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/journaling/Disable or enable journaling of voice mail and missed call notifications
> +Use the PowerShell to disable or enable journaling of voice mail and missed call notifications
```suggestion
Use PowerShell to disable or enable journaling of voice mail and missed call notifications.
```

2020-09-09 23:55 UTC, JohanFreelancer9 requested changes
Copy review is done - I cannot see the rich diff for some reason, so could not check formatting. Unfortunately, I also do not have merge rights.

2020-09-14 18:07 UTC, merged

2020-09-18 21:20 UTC, Tangela123 commented
The Article is still not showing up in the Table of contents