update-create-user-mailbox-task4455945
MicrosoftDocs/OfficeDocs-Exchange pull request #2251
Opened 2020-09-15 06:42 UTC by Lovina-Saldanha

Removed section "How do you know this worked?"

2020-09-16 23:45 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-17 04:45 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/create-user-mailboxes.md
>  After you create a mailbox by running the previous command, an user account is also created. You have to activate this user account by assigning a license. To assign a license in the Microsoft 365 ad
```suggestion
After you create a mailbox by running the previous command, a user account is also created. You have to activate this user account by assigning a license. To assign a license in the Microsoft 365 admin center, see [Add users individually or in bulk](https://docs.microsoft.com/microsoft-365/admin/add-users/add-users).
```

2020-09-17 04:46 UTC, JohanFreelancer9 requested changes
Copy review - although not related to this PR, please also correct the typo in the preceding paragraph as indicated.

2020-09-17 05:31 UTC, JohanFreelancer9 approved these changes

2020-09-18 01:15 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-18 20:03 UTC, merged