Patch 14
MicrosoftDocs/OfficeDocs-Exchange pull request #2259
Opened 2020-09-17 11:45 UTC by Lovina-Saldanha

2020-09-18 01:16 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-18 04:28 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +After you create a user mailbox, you can make changes and set additional properties by using the new Exchange admin center(EAC) or Exchange Online PowerShell.
```suggestion
After you create a user mailbox, you can make changes and set additional properties by using the new Exchange admin center (EAC) or Exchange Online PowerShell.
```

2020-09-18 04:29 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +The **mailboxes** and **shared** tabs under **Recipients** (of the classic EAC) are now merged into a single tab, **Mailboxes** in the new EAC. On clicking the **Mailboxes** tab, you can view the sha
```suggestion
The **mailboxes** and **shared** tabs under **Recipients** (of the classic EAC) are now merged into a single tab, **Mailboxes**, in the new EAC. On clicking the **Mailboxes** tab, you can view the shared and user mailboxes under one list view. On top of the list of shared and user mailboxes, the following options are provided:
```

2020-09-18 04:33 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +   - **Normal List** and **Compact List** - The default view that you see when you open Mailboxes is the normal listing view. In the Compact List view you can see more number of columns with reduced
```suggestion
   - **Normal List** and **Compact List** - The default view that you see when you open Mailboxes is the normal listing view. In the Compact List view, you can see more columns with reduced spaces in between.
```

2020-09-18 04:34 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +   - Also, when you select any mailbox by clicking on the radio button next to the display name(on any row), certain additional options are also available on top:
```suggestion
   - Also, when you select any mailbox by clicking on the radio button next to the display name (on any row), certain additional options are also available on top:
```

2020-09-18 07:16 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +      - Other additional options such as Edit contact information, Manage mailbox delegation, Recover deleted items, Convert to shared mailbox, Edit email address, Refresh etc. are also displayed on
```suggestion
      - Other additional options such as Edit contact information, Manage mailbox delegation, Recover deleted items, Convert to shared mailbox, Edit email address, Refresh, etc. are also displayed on clicking the more options (**...**) button on top.  
```

2020-09-18 07:17 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +4. Use the **Mailbox** link to change any of the following the properties.
```suggestion
4. Use the **Mailbox** link to change any of the following properties:
```

2020-09-18 07:22 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +   - **Make this the reply address**: In Exchange Online, you can select this check box to make the new email address the primary SMTP address for the mailbox. This check box  isn't available in the
```suggestion
   - **Make this the reply address**: In Exchange Online, you can select this check box to make the new email address the primary SMTP address for the mailbox. This check box isn't available in the EAC in Exchange Server. Click OK to save your changes.
```

2020-09-18 07:27 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +Use the **Mailbox policies** section to apply default mailbox policies for the organization. Click **Manage mailbox policies** under **Mailbox policies**. A flyout is displayed and you can view or ch
```suggestion
Use the **Mailbox policies** section to apply default mailbox policies for the organization. Click **Manage mailbox policies** under **Mailbox policies**. A flyout is displayed and you can view or change the mailbox policies. Click ![Edit icon](../../media/ITPro_EAC_EditIcon.gif) and change the following mailbox policies:
```

2020-09-18 07:30 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +- **Sharing policy**: This box shows the sharing policy applied to the mailbox. A sharing policy controls how users in your organization can share calendar and contact information with users outside
```suggestion
- **Sharing policy**: This box shows the sharing policy applied to the mailbox. A sharing policy controls how users in your organization can share calendar and contact information with users outside your Exchange organization. The default sharing policy is assigned to mailboxes when they are created. To change the sharing policy that's assigned to the user, select a different one from the drop-down list.
```

2020-09-18 07:35 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +- **Set recipient limit**: This setting controls the maximum number of recipients the user can send a message to. Specify the maximum number of recipients in the Maximum recipients text box . In Exch
```suggestion
- **Set recipient limit**: This setting controls the maximum number of recipients the user can send a message to. Specify the maximum number of recipients in the **Maximum recipients** text box. In Exchange Online, the limit is 500 recipients.
```

2020-09-18 07:39 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +> [!Note] This field cannot be empty if automatic reply is on.
```suggestion
> [!NOTE]
> This field cannot be empty if automatic reply is on.
```

2020-09-18 07:40 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +- **Send automatic replies to senders outside the organizations from this mailbox** - Enable this check box to send automatic replies to senders outside the organizations from this mailbox. On enabli
```suggestion
- **Send automatic replies to senders outside the organizations from this mailbox** - Enable this check box to send automatic replies to senders outside the organizations from this mailbox. On enabling this check box, you can choose between the options, **Only reply to senders in the mailbox's contact list** or **Reply to all senders**. Enter the automatic reply message in the **Reply to all senders outside the organizations from this mailbox** text box.
```

2020-09-18 07:43 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +Use this section to apply the default settings for outlook for web, IMAP, POP3, MAPI applied. Click **Manage email apps settings** under **Email apps**. A flyout is displayed and you can set the defa
```suggestion
Use this section to apply the default settings for Outlook on the web, IMAP, POP3, and MAPI applied. Click **Manage email apps settings** under **Email apps**. A flyout is displayed and you can set the default settings for the following:
```

2020-09-18 07:44 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/manage-user-mailboxes.md
> +> [!Note] All these fields are enabled by default.
```suggestion
> [!NOTE]
> All these fields are enabled by default.
```

2020-09-18 07:49 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-22 03:02 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-22 14:30 UTC, merged