Patch 13
MicrosoftDocs/OfficeDocs-Exchange pull request #2261
Opened 2020-09-17 13:24 UTC by Lovina-Saldanha

Updated new EAC UI content. Added new sections " Use the new EAC to ädd an email address" and "Use the new EAC to remove an email address"

2020-09-18 01:16 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-18 04:23 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/add-or-remove-email-addresses.md
> +4. In the list of email addresses, select the address you want to remove, and then click the delete button.
```suggestion
4. In the list of email addresses, select the address you want to remove, and then click the **Delete** button.
```

2020-09-18 04:25 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/add-or-remove-email-addresses.md
> +4. In the list of email addresses, select the address you want to remove, and then click the delete button.
```suggestion
4. In the list of email addresses, select the address you want to remove, and then click **Delete**.
```

2020-09-18 04:27 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-22 03:02 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-22 15:49 UTC, merged