Patch 7
MicrosoftDocs/OfficeDocs-Exchange pull request #2263
Opened 2020-09-17 16:00 UTC by Lovina-Saldanha

Added a new section "Use the new EAC to enable or disable Outlook on the web"

2020-09-18 01:16 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-18 04:04 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-outlook-web-app.md
> +4. A flyout **Manage settings for email apps** is displayed. Do one of the following.
```suggestion
4. A flyout **Manage settings for email apps** is displayed. Do one of the following:
```

2020-09-18 04:07 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-outlook-web-app.md
> +2. In the list of user mailboxes, click the mailbox that you want to enable or disable Outlook on the web. A flyout is displayed for the selected user mailbox.
```suggestion
2. In the list of user mailboxes, click the mailbox for which you want to enable or disable Outlook on the web. A flyout is displayed for the selected user mailbox.
```

2020-09-18 04:10 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-22 03:02 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-22 15:56 UTC, merged