Clarifying
MicrosoftDocs/OfficeDocs-Exchange pull request #2267
Opened 2020-09-18 00:43 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1867

2020-09-18 01:16 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-18 03:56 UTC, JohanFreelancer9 approved these changes

2020-09-18 14:56 UTC, get-itips commented
@dariomws please have a look, thanks

2020-09-18 14:57 UTC, get-itips commented
@JohanFreelancer9 ready for final review

2020-09-18 20:21 UTC, dariomws approved these changes

2020-09-19 02:42 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md
> +Using Windows PowerShell, run the following cmdlet, remember to replace the UserPrincipalName:
```suggestion
Using Windows PowerShell, run the following cmdlet and remember to replace the UserPrincipalName:
```

2020-09-19 02:43 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md
> +> The above step uses Exchange Online PowerShell V2 module, for more information, see [Connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online
```suggestion
> The above step uses the Exchange Online PowerShell V2 module. For more information, see [Connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell).
```

2020-09-19 02:47 UTC, JohanFreelancer9 requested changes
Copy review - a few minor edits.

2020-09-22 03:02 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-22 15:58 UTC, merged