Patch 9
MicrosoftDocs/OfficeDocs-Exchange pull request #2270
Opened 2020-09-18 09:39 UTC by Lovina-Saldanha

Added a new section "Use the new EAC to enable or disable Exchange ActiveSync".

2020-09-22 03:08 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-22 10:07 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-exchange-activesync.md
> +## Use the Classic EAC to enable or disable Exchange ActiveSync
```suggestion
## Use the classic EAC to enable or disable Exchange ActiveSync
```

2020-09-22 10:07 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-exchange-activesync.md
> +1. In the Classic EAC, navigate to **Recipients** \> **Mailboxes**.
```suggestion
1. In the classic EAC, navigate to **Recipients** \> **Mailboxes**.
```

2020-09-22 10:08 UTC, JohanFreelancer9 requested changes
Copy review

2020-09-22 10:22 UTC, JohanFreelancer9 approved these changes

2020-09-23 02:40 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-23 15:10 UTC, merged