Patch 11
MicrosoftDocs/OfficeDocs-Exchange pull request #2271
Opened 2020-09-18 11:42 UTC by Lovina-Saldanha

Added a new section "Use the new EAC to configure message delivery restrictions"

2020-09-22 03:08 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-22 10:04 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/configure-message-delivery-restrictions.md
> +## Use the Classic EAC to configure message delivery restrictions
```suggestion
## Use the classic EAC to configure message delivery restrictions
```

2020-09-22 10:04 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/configure-message-delivery-restrictions.md
> +1. In the Classic EAC, navigate to **Recipients** \> **Mailboxes**.
```suggestion
1. In the classic EAC, navigate to **Recipients** \> **Mailboxes**.
```

2020-09-22 10:05 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2020-09-22 10:24 UTC, JohanFreelancer9 approved these changes

2020-09-23 02:40 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-23 15:11 UTC, merged