Update Clean up or delete items from the Recoverable Items folder in EXO article
MicrosoftDocs/OfficeDocs-Exchange pull request #2274
Opened 2020-09-18 15:08 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1774.

2020-09-22 03:08 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-22 07:41 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md
> +3. Use the **New-ComplianceSearch** cmdlet (in Security & Compliance Center PowerShell) or use the Content search tool in the compliance center to create a content search that returns items from the
```suggestion
3. Use the **New-ComplianceSearch** cmdlet (in Security & Compliance Center PowerShell) or use the Content Search tool in the compliance center to create a content search that returns items from the target user's Recoverable Items folder. You can do this by including the FolderId in the search query for all subfolders that you want to search. For example, the following query returns all messages in the Purges and eDiscoveryHolds subfolders:
```

2020-09-22 07:43 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md
> +   > If you use the **New-ComplianceSearch** cmdlet to search the Recoverable Items folder, be sure to use **Start-ComplianceSearch** cmdlet to run the search.
```suggestion
   > If you use the **New-ComplianceSearch** cmdlet to search the Recoverable Items folder, be sure to use the **Start-ComplianceSearch** cmdlet to run the search.
```

2020-09-22 07:47 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md
> +To verify that you've successfully deleted items from the Recoverable Items folder of a mailbox, use the [Get-MailboxFolderStatistics](https://docs.microsoft.com/powershell/module/exchange/get-mailbo
```suggestion
To verify that you've successfully deleted items from the Recoverable Items folder of a mailbox, use the [Get-MailboxFolderStatistics](https://docs.microsoft.com/powershell/module/exchange/get-mailboxfolderstatistics) cmdlet in [Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell) to check the size and number of items in the Recoverable Items folder. You can compare these statistics with the ones you collected in Step 1.
```

2020-09-22 07:48 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2020-09-22 15:29 UTC, JohanFreelancer9 approved these changes

2020-09-23 02:40 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-23 15:14 UTC, merged