Clarifying
MicrosoftDocs/OfficeDocs-Exchange pull request #2296
Opened 2020-10-02 15:24 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1971

2020-10-05 04:27 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-05 13:47 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md
> +   - _Folder to size map path_ equals to the full file path of the .csv file you created when running the `Export-PublicFolderStatistics.ps1` script.
```suggestion
   - _Folder to size map path_ equals the full file path of the .csv file you created when running the `Export-PublicFolderStatistics.ps1` script.
```

2020-10-05 13:48 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-06 05:59 UTC, JohanFreelancer9 approved these changes

2020-10-07 04:58 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-07 15:23 UTC, merged