Update whats-new.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2328
Opened 2020-10-22 15:09 UTC by Swatyario

2020-10-26 04:15 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-26 07:19 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +The admins can now create Groups from the modern EAC. Currently, they can create and manage M365 groups, Distribution groups and Mail-enabled Security groups.
```suggestion
The admins can now create Groups from the modern EAC. Currently, they can create and manage Microsoft 365 groups, Distribution groups, and Mail-enabled Security groups.
```

2020-10-26 07:22 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +3 types of Groups that the admins can now create and manage are:
```suggestion
Three types of groups that the admins can now create and manage are:  
```

2020-10-26 07:24 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +## September 2020 (Ignite Release)
```suggestion
## September 2020 (Ignite release) 
```

2020-10-26 07:25 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +### Groups – Creation and Management
```suggestion
### Groups – creation and management 
```

2020-10-26 07:28 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +**M365 Groups** – They are the recommended Group type and they allow for effective collaboration by providing them shared email and a shared workplace.
```suggestion
**Microsoft 365 groups** – They are the recommended group type and they allow for effective collaboration by providing shared email and a shared workplace. 
```

2020-10-26 07:29 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +**Distribution Groups** – They are the most used Group type and they allow you to send email to all members of the list.
```suggestion
**Distribution groups** – They are the most used group type and they allow you to send email to all members on the list. 
```

2020-10-26 07:30 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +**Mail-enabled Security Groups** – They give the members access to various resources like OneDrive, SharePoint and admin roles.
```suggestion
**Mail-enabled security groups** – they give the members access to various resources like OneDrive, SharePoint, and admin roles. 
```

2020-10-26 07:37 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +### Normal/Compact list view in Groups
```suggestion
### Normal/Compact list view in groups 
```

2020-10-26 07:38 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +The admins can now choose to view the list of groups in normal or compact list view way. Compact list option allows the admins to view more entries per page.
```suggestion
Admins can now choose to view the list of groups in normal or compact list view. The compact list option allows admins to view more entries per page. 
```

2020-10-26 07:40 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +### Naming Policy for Groups
```suggestion
### Naming Policy for groups 
```

2020-10-26 07:42 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +The admins now have command over the Group naming policy. They can now add prefixes and suffixes for the future groups that will be created. They can also block specific words from being used in grou
```suggestion
Admins now have command over the group naming policy. They can now add prefixes and suffixes for the future groups that will be created. They can also block specific words from being used in group names and aliases. 
```

2020-10-26 07:42 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +### Upgrade Distribution Group
```suggestion
### Upgrade distribution group 
```

2020-10-26 07:45 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +The admins can now upgrade the distribution groups into the recommended Microsoft 365 (previously O 365 groups) with few clicks.
```suggestion
Admins can now upgrade the distribution groups into the recommended Microsoft 365 groups (previously Office 365 groups) with a few clicks. 
```

2020-10-26 07:51 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +The users now have a single click Opt-in toggle button available in classic and the new Exchange Admin Center. The button allows for easy navigation between two portals and now users can try and acce
```suggestion
The users now have a single click **Opt-in** toggle button available in the classic and the new Exchange admin center. The button allows for easy navigation between two portals and now users can access the new portal seamlessly. 
```

2020-10-26 07:52 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +### Support Assistant
```suggestion
### Support assistant 
```

2020-10-26 07:54 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +### Educational Navigation Video
```suggestion
### Educational navigation video 
```

2020-10-26 08:00 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +An educational navigation video is now available on the very first tile ‘Training and Guide’ in the new EAC portal. The video allows the users to understand the basic navigation of the new portal. Yo
```suggestion
An educational navigation video is now available on the very first tile "Training and Guide" in the new EAC portal. The video allows the users to understand the basic navigation of the new portal. You can also access the video [here](https://www.microsoft.com/videoplayer/embed/RE4FqDa.
```

2020-10-26 08:01 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +### Recipients – MS Documents Updated
```suggestion
### Recipients – Microsoft documents updated 
```

2020-10-26 08:03 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/whats-new.md
> +Going forward with helping the users with their queries related to new Exchange Admin Center portal, the Microsoft documentation is also complete for the high traffic pages under Recipients.
```suggestion
In moving forward to help the users with their queries related to the new Exchange admin center portal, we have also completed the Microsoft documentation for high traffic pages under "Recipients".
```

2020-10-26 08:14 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-27 07:26 UTC, Swatyario commented
Hi Johan, Thanks for suggesting these important changes. I will take care of that in my next post. Btw, I was not able to add pictures in the blog. Here is the link of the Word Doc:

https://microsoft-my.sharepoint.com/:w:/p/adbhale/ETytKyo0LKxAlYAmpUt2CR0BrenUfm3yuUd09q3TidM6Cg?e=tbhsr8

Could you please help me add the images as well at the respective places?

2020-10-28 02:20 UTC, JohanFreelancer9 approved these changes
Thank you, looks good. Unfortunately, I am not able to assist with linking the images. @scanum?

2020-10-28 04:14 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-02 15:39 UTC, msdmaguire commented
@Swatyario, apologies that this PR fell through the cracks. I am closing this because in the interim I have worked with Aditya to update the What's new article in both September and December of 2020. If there are still gaps, please open a new PR and ping me directly when it is ready and I'll push it through.

2021-02-02 15:39 UTC, closed without merging