Update plus-addressing-in-exchange-online.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2342
Opened 2020-11-04 20:55 UTC by SeanMSFT

Adding clarification notes

2020-11-06 03:37 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-06 07:51 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md
> +>[!NOTE]
```suggestion
> [!NOTE]
```

2020-11-06 07:52 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md
> +> Currently, plus addresses are only supported for mailboxes but support for Groups and DLs is being rolled out and will be available by the end of December 2020.
```suggestion
> Currently, plus addresses are only supported for mailboxes but support for Groups and distribution lists is being rolled out and will be available by the end of December 2020. 
```

2020-11-06 07:52 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md
> +>[!NOTE]
```suggestion
> [!NOTE]
```

2020-11-06 07:56 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md
> +> This feature was rolled out behind a setting because, historically, customers have been able to use plusses in addresses for mailboxes in Exchange Online and on-premises servers. When this feature
```suggestion
> This feature was rolled out behind a setting because, historically, customers have been able to use plusses in addresses for mailboxes in Exchange Online and on-premises servers. When this feature is enabled, Exchange Online will first check if the full address can resolve to a mailbox that the service is aware of. It is only when that resolution fails that a plus is looked for and a second attempt to resolve the address without the plus and tag is done. This means that the feature is compatible with addresses containing plusses that Exchange Online knows about. If you relay messages to a mailbox on-premises that does not resolve in Exchange Online, message delivery will be affected. The messages will be parsed and addressed to the parsed address, e.g. sean@contoso.com instead of the full sean+newsletter@contoso.com, using the example above.  
```

2020-11-06 07:56 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2020-11-09 04:52 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-09 18:21 UTC, merged