Removed Shared Mailboxes sentence in configure-email-forwarding.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2352
Opened 2020-11-12 12:35 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2348.

2020-11-16 06:56 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-17 00:33 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/configure-email-forwarding.md
>  > If you're using Microsoft 365 or Office 365 for business, you should configure email forwarding in the [Configure email forwarding](https://docs.microsoft.com/microsoft-365/admin/email/configure-em
```suggestion
> If you're using Microsoft 365 or Office 365 for business, you should configure email forwarding in the [Configure email forwarding](https://docs.microsoft.com/microsoft-365/admin/email/configure-email-forwarding).
```

2020-11-17 00:33 UTC, JohanFreelancer9 requested changes
Copy review - minor additional edit, please.

2020-11-17 03:48 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-17 16:11 UTC, merged