Update configure-im-integration-with-owa.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2353
Opened 2020-11-13 15:53 UTC by TreaHorton

Updating this integration when the Exchange IIS Certificate is changed or renewed is a pain point for our customers
Often they end up creating a new override instead of updating the existing one as our documentation isn't clear to them
Recommend we add a section in this article to address that common scenario
Add new "Use the Exchange Management Shell to update the existing IM integration with Outlook on the Web when the Exchange IIS Certificate is renewed or changed" section

2020-11-16 06:56 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-17 00:14 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/configure-im-integration-with-owa.md
> +Use the following syntax in the Exchange Management Shell to specify new IM certificate thumbprint:
```suggestion
Use the following syntax in the Exchange Management Shell to specify the new IM certificate thumbprint:
```

2020-11-17 00:22 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/configure-im-integration-with-owa.md
> +## Use the Exchange Management Shell to update the existing IM integration with Outlook on the Web when the Exchange IIS Certificate is renewed or changed
```suggestion
## Use the Exchange Management Shell to update the existing IM integration with Outlook on the web when the Exchange IIS certificate is renewed or changed
```

2020-11-17 00:25 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/configure-im-integration-with-owa.md
> +- **Setting override name**: "IM Override" (must use the one already in place from previous steps since we are updating, not creating new)
```suggestion
- **Setting override name**: "IM Override" (you must use the one already in place from previous steps since we are updating, not creating a new name)
```

2020-11-17 00:29 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-17 03:49 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-17 16:25 UTC, merged