Adding option to configure proxy
MicrosoftDocs/OfficeDocs-Exchange pull request #2356
Opened 2020-11-16 16:54 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1598

@dariomws Can you please review? Thanks

2020-11-16 20:56 UTC, dariomws approved these changes

2020-11-17 03:48 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-17 09:23 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md
> +By running the script the following section will be added to Microsoft.Online.EME.Hybrid.Agent.Service.exe.config file located on the same folder:
```suggestion
By running the script, the following section will be added to the Microsoft.Online.EME.Hybrid.Agent.Service.exe.config file located in the same folder:
```

2020-11-17 09:24 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-18 02:22 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-18 02:52 UTC, JohanFreelancer9 approved these changes

2020-11-18 16:17 UTC, merged