Update hybrid-configuration-wizard.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2370
Opened 2020-11-25 12:26 UTC by mukeshHCW

The role required to run HCW must be global admin in M365. This is the correction made here. 

_Please reach out to mukkum@microsoft.com for any clarification_

2020-11-26 19:31 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-27 04:46 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-configuration-wizard.md
> +2. **Testing account credentials**: Designated on-premises and Microsoft 365 or Office 365 hybrid management accounts access the on-premises and Exchange Online organizations to gather prerequisite v
```suggestion
2. **Testing account credentials**: Designated on-premises and Microsoft 365 or Office 365 hybrid management accounts access the on-premises and Exchange Online organizations to gather prerequisite verification information and to make organization parameter configuration changes to enable hybrid deployment functionality. The Hybrid Configuration wizard checks that the accounts have the appropriate credentials and can connect to the on-premises and Exchange Online organizations. The hybrid deployment management accounts for on-premises organizations must be members of the Organization Management role group and must be Global Admins for Microsoft 365 or Office 365 organizations for the Hybrid Configuration wizard to complete these tasks successfully.
```

2020-11-27 04:51 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-27 05:54 UTC, JohanFreelancer9 approved these changes

2020-12-01 02:07 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-01 17:18 UTC, merged