Update activate-lagged-db-copies.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2382
Opened 2020-12-02 13:13 UTC by andreig2735

2020-12-04 04:32 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-04 08:52 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/high-availability/manage-ha/activate-lagged-db-copies.md
> +Note: if the database being recovered is "out of place", make sure to specify the logfile,checkpoint and database paths in the eseutil command, for example:
```suggestion
**Note**: If the database being recovered is "out of place", make sure to specify the log file, checkpoint, and database paths in the eseutil command, for example:
```

2020-12-04 08:53 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-07 05:17 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-07 16:33 UTC, merged