Added Domain feature to feature-permissions.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2407
Opened 2020-12-14 18:24 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2394.

2020-12-16 04:44 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-16 08:45 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/permissions-exo/feature-permissions.md
>  |In-Place eDiscovery|Discovery Management  <br/> **Note**: By default, the Discovery Management role group doesn't have any members. No users, including adminis, have the required permissions to sear
```suggestion
|In-Place eDiscovery|Discovery Management  <br/> **Note**: By default, the Discovery Management role group doesn't have any members. No users, including admins, have the required permissions to search mailboxes. For more information, see [Assign eDiscovery permissions in Exchange](../security-and-compliance/in-place-ediscovery/assign-ediscovery-permissions.md).|
```

2020-12-16 08:47 UTC, JohanFreelancer9 requested changes
Copy review - unrelated, but please also correct the typo in Line 55.

2020-12-17 06:22 UTC, JohanFreelancer9 approved these changes

2020-12-21 04:22 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-21 16:03 UTC, merged