SIR does not retain COW items instead Litigation Hold.
MicrosoftDocs/OfficeDocs-Exchange pull request #2425
Opened 2020-12-30 06:51 UTC by sujnai

Here is the statement from the article:
Also, if a message is changed by a user or a process, copies of the original item are also retained when single item recovery is enabled. 

Here is what we need to update:
Also, if a message is changed by a user or a process, copies of the original item are also retained when single item recovery and Litigation Hold both are enabled.

This is applicable for both Exchange Server 2013, 2016, 2019 and Exchange Online. All reference articles for Single Item Recovery needs to be updated for related products.

2021-01-03 05:38 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-03 09:54 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer2013/enable-or-disable-single-item-recovery-exchange-2013-help.md
> +You can use the Shell to enable or disable single item recovery on a mailbox. In Exchange Server, single item recovery is disabled when a mailbox is created. If single item recovery is enabled, messa
```suggestion
You can use the Shell to enable or disable single item recovery on a mailbox. In Exchange Server, single item recovery is disabled when a mailbox is created. If single item recovery is enabled, messages that are permanently deleted (purged) by the user are retained in the Recoverable Items folder of the mailbox until the deleted item retention period expires. This lets an administrator recover messages purged by the user before the deleted item retention period expires. Also, if a message is changed by a user or a process, copies of the original item are also retained when both single item recovery and Litigation Hold are enabled.
```

2021-01-03 09:56 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-01-04 04:59 UTC, sujnai commented on Exchange/ExchangeServer2013/enable-or-disable-single-item-recovery-exchange-2013-help.md
> +You can use the Shell to enable or disable single item recovery on a mailbox. In Exchange Server, single item recovery is disabled when a mailbox is created. If single item recovery is enabled, messa
Looks good.

2021-01-04 13:55 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer2013/enable-or-disable-single-item-recovery-exchange-2013-help.md
> +You can use the Shell to enable or disable single item recovery on a mailbox. In Exchange Server, single item recovery is disabled when a mailbox is created. If single item recovery is enabled, messa
@sujnai could you please commit my change? Thanks.

2021-01-04 14:35 UTC, sujnai commented on Exchange/ExchangeServer2013/enable-or-disable-single-item-recovery-exchange-2013-help.md
> +You can use the Shell to enable or disable single item recovery on a mailbox. In Exchange Server, single item recovery is disabled when a mailbox is created. If single item recovery is enabled, messa
The change looks fine @JohanFreelancer9 .

2021-01-04 14:40 UTC, sujnai commented on Exchange/ExchangeServer2013/enable-or-disable-single-item-recovery-exchange-2013-help.md
> +You can use the Shell to enable or disable single item recovery on a mailbox. In Exchange Server, single item recovery is disabled when a mailbox is created. If single item recovery is enabled, messa
@JohanFreelancer9 I can see there are other versions of Article for Exchange 2016 and Exchange 2019 as well which needs to be updated with same correction. Should there be a separate pull request created?
https://docs.microsoft.com/en-us/Exchange/recipients/user-mailboxes/single-item-recovery?view=exchserver-2019
https://docs.microsoft.com/en-us/Exchange/recipients/user-mailboxes/single-item-recovery?view=exchserver-2016

2021-01-05 02:43 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-05 03:39 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer2013/enable-or-disable-single-item-recovery-exchange-2013-help.md
> +You can use the Shell to enable or disable single item recovery on a mailbox. In Exchange Server, single item recovery is disabled when a mailbox is created. If single item recovery is enabled, messa
@sujnai - yes, separate pull requests should be created for them. Many thanks.

2021-01-05 03:40 UTC, JohanFreelancer9 approved these changes

2021-01-05 16:09 UTC, merged