Update journaling.md with duplicate journal report scenarios
MicrosoftDocs/OfficeDocs-Exchange pull request #2444
Opened 2021-01-12 03:32 UTC by jamesmilford

Per VSO 1747880, the Exchange PG provided known scenarios in which duplicate journal reports may occur in a hybrid Exchange environment (on-premises and cloud). They requested I create a pull request to include those scenarios in this document. I initially located this information in the Troubleshooting section, but feel free to move it elsewhere and flesh it out further.  I've never hear the term chipping that is noted in scenario 1a, so this may need to be changed to a more common term or further explained in the document. Also, should "duplicate" or "multiple" be used here? In most cases, it would just be duplicate journal reports being generated, one in on-prem and the other in the cloud.

Contact @cabailey or Nakul Garg (nakulg) for follow-up on this item.

2021-01-18 05:10 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-18 07:16 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md
> +In an Exchange hybrid environment, the following scenarios are known to result in duplicate journal reports and these are considered by design:
```suggestion
In a hybrid Exchange environment, the following scenarios are known to result in duplicate journal reports and these are considered by design:
```

2021-01-18 07:17 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md
> +>1. Cloud to Cloud: Any situations where email is forked will lead to duplicate journaling, such as:
```suggestion
1. **Cloud to cloud**: Any situations where email is forked will lead to duplicate journaling, such as:
```

2021-01-18 07:18 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md
> +>>>a. Transport chipping (too many recipients on the message).
```suggestion
- Transport chipping (too many recipients on the message).
```

2021-01-18 07:19 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md
> +>>>b. Internal and External recipients exist on the same message – two forks are created for spam/phishing purposes (one in which internal recipients exist, and one in which external recipients exist
```suggestion
- Internal and external recipients exist on the same message – two forks are created for spam/phishing purposes (one in which internal recipients exist, and one in which external recipients exist).
```

2021-01-18 07:19 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md
> +>>>c. Any future needs where cloud needs to fork the message.
```suggestion
- Any future needs where the cloud needs to fork the message.
```

2021-01-18 07:36 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md
> +>2. OnPrem to Cloud: Once when onprem journals and once when cloud journals. This can be prevented by implenting the PreventDupJournaling flight in a tenant.
```suggestion
>2. On-premises to cloud: Once when on-premises journals and once when the cloud journals. This can be prevented by implementing the PreventDupJournaling flight in a tenant.
```

2021-01-18 07:40 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md
> +>3. Cloud to OnPrem: After cloud has journaled, then on-prem journaled. We cannot prevent this scenario.
```suggestion
3. **Cloud to on-premises**: After the cloud has journaled, on-premises journals. We cannot prevent this scenario.
```

2021-01-18 07:41 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-21 03:49 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-22 16:09 UTC, merged