SkippedItem handling updates
MicrosoftDocs/OfficeDocs-Exchange pull request #2485
Opened 2021-02-18 02:13 UTC by wrall

Update documentation about DataConsistencyScore and improve skipped item documentation

2021-02-19 03:31 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-19 06:23 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md
> +   > [!NOTE]
```suggestion
> [!NOTE]
```

2021-02-19 06:23 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md
> +   > It is recommended that MRM and Archive policies are disabled for these users until after the migration for those users has been completed.  When such features remain enabled during migration, th
```suggestion
> We recommend that the Default MRM Policy and Archive policies be disabled for these users until after their migration has been completed.  When such features remain enabled during migration, there is a chance that some messages will end up being considered "missing" during the content verification process.
```

2021-02-19 06:25 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md
> +|**Good**|At least 1 inconsistency noted, but the data loss was not impactful. For example, if only metadata or folder permissions were lost during migration. The migration will succeed.|
```suggestion
|**Good**|At least 1 inconsistency noted, but the data loss was not impactful. For example, only metadata or folder permissions were lost during migration. The migration will succeed.|
```

2021-02-19 06:29 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md
> +1. In the Exchange Admin center, click **recipients**, and then click **migration**.
```suggestion
1. In the Exchange admin center, select **Recipients** > **Migration**.
```

2021-02-19 06:30 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md
> +2. Select the batch you would like to inspect. Click **View details** in the information pane on the right.
```suggestion
2. Select the batch you would like to inspect. Choose **View details** in the information pane on the right.
```

2021-02-19 06:30 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md
> +3. Select the user you would like to inspect. Click **Skipped item details** in the information pane on the right.
```suggestion
3. Select the user you would like to inspect. Select **Skipped item details** in the information pane on the right.
```

2021-02-19 06:33 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md
> +1. In the Exchange Admin center, click **recipients**, and then click **migration**.
```suggestion
1. In the Exchange admin center, click **Recipients**, and then click **Migration**.
```

2021-02-19 06:36 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md
> +1. In the Exchange Admin center, click **recipients**, and then click **migration**.
Please confirm capitalization of "Recipients" and "Migration".

2021-02-19 06:38 UTC, JohanFreelancer9 requested changes
Copy review - suggestions only.

2021-02-20 01:51 UTC, wrall commented on Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md
> +|**Good**|At least 1 inconsistency noted, but the data loss was not impactful. For example, if only metadata or folder permissions were lost during migration. The migration will succeed.|
This statement actually applies better to the first sentence than the second.

2021-02-20 01:51 UTC, wrall commented on Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md
> +1. In the Exchange Admin center, click **recipients**, and then click **migration**.
I copied and pasted this line from another article.  In classic EAC the titles are all lower-case.

2021-02-20 02:04 UTC, wrall commented on Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md
> +|**Good**|At least 1 inconsistency noted, but the data loss was not impactful. For example, if only metadata or folder permissions were lost during migration. The migration will succeed.|
I'll separate it out into a different column for clarity as to why this is mentioned.

2021-02-20 03:05 UTC, JohanFreelancer9 approved these changes

2021-02-21 22:47 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-02-22 16:15 UTC, merged