Clarify the necessity of completing a batch
MicrosoftDocs/OfficeDocs-Exchange pull request #2533
Opened 2021-03-24 08:52 UTC by matsimon

The new EAC section is missing the actual explanation on what completion does, I've copied
it from the part for legacy EAC.

Emphasizing the necessity of the completion and explaining it in the section what does actually happen during
that phase avoids unnecessary trial-and-errors simple because one did not cross-check the differences between the 3 available
ways (New admin, old admin, Powershell).

2021-03-24 19:20 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-25 07:04 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md
> +During completion, another incremental sync is run to copy any changes that have been made to the Google Workspace mailbox. Additionally, during completion, the forwarding address that routes mail fr
```suggestion
During completion, another incremental sync is run to copy any changes that have been made to the Google Workspace mailbox. Additionally, during completion, the forwarding address that routes mail from Microsoft 365 or Office 365 to Google Workspace is removed, and a forwarding address that routes mail from Google Workspace to Microsoft 365 or Office 365 is added. This ensures that any messages received by migrated users at their Google Workspace mailboxes will be sent to their new Microsoft 365 or Office 365 address. Similarly, if any user who has not yet been migrated receives a message at their Microsoft 365 or Office 365 address, the message will get routed to their Google Workspace mailbox.
```

2021-03-25 07:07 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md
> +During completion, another incremental sync is run to copy any changes that have been made to the Google Workspace mailbox. Additionally, during completion, the forwarding address that routes mail fr
```suggestion
During completion, another incremental sync is run to copy any changes that have been made to the Google Workspace mailbox. Additionally, during completion, the forwarding address that routes mail from Microsoft 365 or Office 365 to Google Workspace is removed, and a forwarding address that routes mail from Google Workspace to Microsoft 365 or Office 365 is added. This ensures that any messages received by migrated users at their Google Workspace mailboxes will be sent to their new Microsoft 365 or Office 365 address. Similarly, if any user who has not yet been migrated receives a message at their Microsoft 365 or Office 365 address, the message will get routed to their Google Workspace mailbox.
```

2021-03-25 07:10 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md
>  During completion, another incremental sync is run to copy any changes that have been made to the Google Workspace mailbox. Additionally, the forwarding address that routes mail from O365 to Google W
```suggestion
During completion, another incremental sync is run to copy any changes that have been made to the Google Workspace mailbox. Additionally, the forwarding address that routes mail from Office 365 to Google Workspace is removed, and a forwarding address that routes mail from Google Workspace to Office 365 is added.
```

2021-03-25 07:11 UTC, JohanFreelancer9 requested changes
Copy review - please commit the few minor edits. Thanks.

2021-03-25 09:17 UTC, matsimon commented on Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md
> +During completion, another incremental sync is run to copy any changes that have been made to the Google Workspace mailbox. Additionally, during completion, the forwarding address that routes mail fr
Fine with me, that spacing is actually coming from the legacy EAC section.

2021-03-25 09:20 UTC, matsimon commented on Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md
>  During completion, another incremental sync is run to copy any changes that have been made to the Google Workspace mailbox. Additionally, the forwarding address that routes mail from O365 to Google W
Thanks, that's currently part of the documentation. Wouldn't it even be better to use Microsoft 365 instead since Microsoft is trying to get rid of all the Office 365 branding?

2021-03-25 09:21 UTC, matsimon commented
Thanks @JohanFreelancer9 I'm overall fine with your suggestions, let's check if you also want to move from the Office 365 wording to Microsoft 365 as it has happened all over the place since the last year. ;-)

2021-03-25 16:54 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md
>  During completion, another incremental sync is run to copy any changes that have been made to the Google Workspace mailbox. Additionally, the forwarding address that routes mail from O365 to Google W
True, but Office 365 still exists. I realize that this is part of the current documentation, but O365 is definitely a no-no, especially since Office 365 has been used throughout the rest of the topic. I am not sure if the paragraph refers specifically to Office 365, or if it can be changed to Microsoft 365, so I would hesitate to change it. Thanks for your input, though.

2021-03-25 17:16 UTC, matsimon commented on Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md
>  During completion, another incremental sync is run to copy any changes that have been made to the Google Workspace mailbox. Additionally, the forwarding address that routes mail from O365 to Google W
It is interesting that no one picked this mishap up except now, when I made a verbatim copy of the legacy section ;-)
Thanks!

2021-03-25 17:18 UTC, matsimon commented
Thank you for your feedback @JohanFreelancer9 , all suggestions have been integrated.

2021-03-29 04:47 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-29 06:56 UTC, JohanFreelancer9 approved these changes

2021-03-30 15:22 UTC, merged