Additional detail about Centralized Mail transport
MicrosoftDocs/OfficeDocs-Exchange pull request #2547
Opened 2021-03-31 14:18 UTC by JuanGasca

The article says "you can route all mail from mailboxes in Exchange online" but the emails coming form internet will be routed to on-premises as well, if centralized mail flow is enabled. I've added the additional information there. 

Technical reference: 
https://docs.microsoft.com/en-us/exchange/transport-routing#inbound-messages-from-the-internet

2021-04-05 05:13 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-05 07:57 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/transport-options.md
> +    With centralized mail transport, you can route all mail from mailboxes in the Exchange Online organization through the on-premises organization before they're delivered to the Internet. The same
```suggestion
    With centralized mail transport, you can route all mail from mailboxes in the Exchange Online organization through the on-premises organization before they're delivered to the Internet. In the same way, incoming Internet messages will be routed to an on-premises organization before being delivered to any Exchange Online recipient. Possible scenarios are detailed in [Transport routing in Exchange hybrid deployments](https://docs.microsoft.com/microsoft-365/compliance/sensitive-information-type-entity-definitions?view=o365-worldwide).
```

2021-04-05 07:57 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-06 02:09 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-06 17:24 UTC, merged