Update integrate-sensitive-information-rules.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2548
Opened 2021-04-02 19:57 UTC by kellybos

Should link to sensitive information type definitions in SCC, not Exchange server.

2021-04-05 05:13 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-05 07:41 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/integrate-sensitive-information-rules.md
> +[Sensitive information types entity definitions] (https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitive-information-type-entity-definitions?view=o365-worldwide)
```suggestion
[Sensitive information type entity definitions] (https://docs.microsoft.com/microsoft-365/compliance/sensitive-information-type-entity-definitions?view=o365-worldwide)
```

2021-04-05 07:41 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-06 02:09 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-06 17:25 UTC, merged