Added note w.r.t On-Premises mailbox's experience
MicrosoftDocs/OfficeDocs-Exchange pull request #2554
Opened 2021-04-08 09:34 UTC by Batre-MSFT

Added note to clarify what will be On-Premises mailbox experience be after steps in this article are performed

2021-04-12 15:23 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-13 06:01 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-microsoft-365-groups.md
> +After the steps of this article are successfully performed, the On-Premises mailbox can send and receive emails to Microsoft 365 Group. However, the Microsoft 365 Group will not appear in the navigat
```suggestion
After the steps of this article are successfully performed, the On-Premises mailbox can send and receive emails to and from a Microsoft 365 Group. However, the Microsoft 365 Group will not appear in the navigation bar of Outlook on the web or Outlook desktop client. For a full-fledged Microsoft 365 Group experience, the mailbox must be present in Microsoft 365. 
```

2021-04-13 06:07 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-13 07:11 UTC, JohanFreelancer9 approved these changes

2021-04-14 05:17 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-14 08:45 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-microsoft-365-groups.md
> +After the steps of this article are successfully performed, the on-premises mailbox can send and receive emails to and from a Microsoft 365 group. However, the Microsoft 365 group will not appear in
```suggestion
After the steps in this article are successfully performed, the on-premises mailbox can send and receive emails to and from a Microsoft 365 group. However, the Microsoft 365 group will not appear in the navigation bar of Outlook on the web or Outlook desktop client. For a fully-fledged Microsoft 365 Groups experience, the mailbox must be present in Microsoft 365. 
```

2021-04-14 08:46 UTC, JohanFreelancer9 requested changes
Apologies @Batre-MSFT - one more minor change, please.

2021-04-14 15:24 UTC, merged