Adding useful link
MicrosoftDocs/OfficeDocs-Exchange pull request #2565
Opened 2021-04-16 23:23 UTC by get-itips

@dariomws What do you think about this addition?

2021-04-19 04:48 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-19 05:20 UTC, JohanFreelancer9 approved these changes

2021-04-19 08:06 UTC, dariomws commented
@get-itips I think the user is confused about how a cutover migration works. There is no integration between Exchange Online and on-premises. Therefore, after you finish all these steps (cutover migration is complete), you need to configure new Outlook profiles. During the profile configuration wizard, it will connect to Exchange Online autodiscover because you cleaned the AutodiscoverInternalUri, and created a CNAME to point to EXO.

Maybe it's a good idea to add a sentence or note that you need to create new Outlook profiles.

2021-04-19 12:29 UTC, get-itips commented
> @get-itips I think the user is confused about how a cutover migration works. There is no integration between Exchange Online and on-premises. Therefore, after you finish all these steps (cutover migration is complete), you need to configure new Outlook profiles. During the profile configuration wizard, it will connect to Exchange Online autodiscover because you cleaned the AutodiscoverInternalUri, and created a CNAME to point to EXO.
> 
> Maybe it's a good idea to add a sentence or note that you need to create new Outlook profiles.

You are right, thanks, can you take a look now?

2021-04-19 14:20 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md
> +9. The administrator sends a welcome letter to users to tell them about Microsoft 365 or Office 365 and to describe how to sign in to their new mailboxes. (See [Create an Outlook profile](https://sup
```suggestion
9. The administrator sends a welcome letter to users to tell them about Microsoft 365 or Office 365 and to describe how to sign in to their new mailboxes. See [Create an Outlook profile](https://support.microsoft.com/office/create-an-outlook-profile-f544c1ba-3352-4b3b-be0b-8d42a540459d) and [Overview of Outlook e-mail profiles](https://support.microsoft.com/office/overview-of-outlook-e-mail-profiles-9073a8ac-c3d6-421d-b5b9-fcedff7642fc) for information on creating new Outlook profiles.
```

2021-04-19 14:21 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-19 14:48 UTC, dariomws approved these changes
Maybe with the Overview article is enough.

2021-04-20 21:27 UTC, scanum commented
@Kateyanne 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-20 22:03 UTC, merged