Remove references and links to Exchange Server
MicrosoftDocs/OfficeDocs-Exchange pull request #2575
Opened 2021-04-22 15:29 UTC by kellybos

There are multiple links to Exchange Server DLP content about built in sensitive information types that is out of date as of December 2020. There is a separate article for Exchange Server (https://docs.microsoft.com/en-us/exchange/policy-and-compliance/data-loss-prevention/data-loss-prevention?view=exchserver-2019) and this article exists in Exchange Online area so we should remove references and links to Exchange Server.

2021-04-26 06:34 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-26 10:11 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md
> +When you create or change DLP policies, you can include rules that include checks for sensitive information. The sensitive information types listed in the [Sensitive information type entity definitio
```suggestion
When you create or change DLP policies, you can include rules that include checks for sensitive information. The sensitive information types listed in the [Sensitive information type entity definitions](https://docs.microsoft.com/microsoft-365/compliance/sensitive-information-type-entity-definitions?view=o365-worldwide) topic are available to be used in your policies. The conditions that you establish within a policy, such as how many times something has to be found before an action is taken or exactly what that action is can be customized within your new custom policies in order to meet your specific policy requirements. For more information about creating DLP policies, see [Create a custom DLP policy](create-custom-dlp-policy.md). For more information about the full suite mail flow rules, see [Mail flow rules (transport rules) in Exchange Online](../../security-and-compliance/mail-flow-rules/mail-flow-rules.md).
```

2021-04-26 10:13 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md
> +To make it easy for you to make use of the sensitive information-related rules, Microsoft has supplied policy templates that already include some of the sensitive information types. You cannot add co
```suggestion
To make it easy for you to make use of the sensitive information-related rules, Microsoft has supplied policy templates that already include some of the sensitive information types. You cannot add conditions for all of the sensitive information types listed here to policy templates however, because the templates are designed to help you focus on the most common types of compliance-related data within your organization. For more information about the pre-built templates, see [DLP policy templates supplied in Exchange](dlp-policy-templates.md). You can create numerous DLP policies for your organization and have them all enabled so that many disparate types of information are examined. You can also create a DLP policy that is not based on an existing template. To begin creating such a policy, see [Create a custom DLP policy](create-custom-dlp-policy.md). For more information about sensitive information types, see [Sensitive information type entity definitions](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitive-information-type-entity-definitions?view=o365-worldwide).
```

2021-04-26 10:15 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md
> +To make it easy for you to make use of the sensitive information-related rules, Microsoft has supplied policy templates that already include some of the sensitive information types. You cannot add co
Please change "most-common" to "most common" in the fourth line.

2021-04-26 10:19 UTC, JohanFreelancer9 requested changes
Copy review - please remove the locale from the link and two more additional edits, please.

2021-04-26 14:56 UTC, JohanFreelancer9 approved these changes

2021-04-29 05:14 UTC, scanum approved these changes

2021-04-29 05:15 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-29 16:42 UTC, merged