Restore from discovery holds
MicrosoftDocs/OfficeDocs-Exchange pull request #2600
Opened 2021-05-10 15:24 UTC by Batre-MSFT

Added information and steps to restore folders from discovery holds

2021-05-12 03:59 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-12 07:38 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/collaboration-exo/public-folders/restore-deleted-public-folder.md
> +For scenarios where public folder contents are put on hold using retention policy, the folders reomved from `\NON_IPM_SUBTREE\DUMPSTER_ROOT` are preserved under `\NON_IPM_SUBTREE\DiscoveryHolds` till
```suggestion
For scenarios where public folder contents are put on hold using retention policy, the folders removed from `\NON_IPM_SUBTREE\DUMPSTER_ROOT` are preserved under `\NON_IPM_SUBTREE\DiscoveryHolds` until the retention hold period is over.
```

2021-05-12 07:39 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/collaboration-exo/public-folders/restore-deleted-public-folder.md
> +Any folders preserved in the public folder dumpster or under DiscoverHolds folder can be restored using EXO PowerShell. Restoring the public folder will restore all subfolders and items present in th
```suggestion
Any folders preserved in the public folder dumpster or under the DiscoverHolds folder can be restored using EXO PowerShell. Restoring the public folder will restore all subfolders and items present in the folder.
```

2021-05-12 07:49 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/collaboration-exo/public-folders/restore-deleted-public-folder.md
> +In this another example, to restore a public folder named `Sales` to the root of the public folder tree:
```suggestion
    The following alternate example restores a public folder named `Sales` to the root of the public folder tree:
```

2021-05-12 07:50 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/collaboration-exo/public-folders/restore-deleted-public-folder.md
> +    ```PowerShell
```suggestion
    ```PowerShell
```

2021-05-12 07:53 UTC, JohanFreelancer9 requested changes
Copy review. @Batre-MSFT, please commit my suggested changes if you agree with them. any thanks.

2021-05-12 11:12 UTC, JohanFreelancer9 commented
@Batre-MSFT - Could you please commit my first suggested change as well (Any folders preserved...)? Thanks.

2021-05-12 11:20 UTC, JohanFreelancer9 approved these changes

2021-05-17 18:06 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-08 01:27 UTC, lweathermon approved these changes

2021-06-08 01:27 UTC, lweathermon approved these changes

2021-06-08 01:28 UTC, lweathermon approved these changes

2021-06-11 17:33 UTC, merged