Update enable-mail-flow-for-subdomains.md  // Add Modern Public Folder Mailrouting feature
MicrosoftDocs/OfficeDocs-Exchange pull request #2602
Opened 2021-05-11 06:10 UTC by FriedrichTobiasCC

> - In order to send mails to Modern Public Folders within your Exchange Online Environment you need to set the domain type to internal relay if the domain contains recipientaddresses assigned to Public Folders. Directory Based Edge Blocking is cannot be used for Modern Public Folders. 

should be added, as this seems to be a common problem

2021-05-12 03:59 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-12 07:28 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/enable-mail-flow-for-subdomains.md
> +> - In order to send mails to Modern Public Folders within your Exchange Online Environment you need to set the domain type to internal relay if the domain contains recipientaddresses assigned to Pub
```suggestion
> - In order to send email to public folders within your Exchange Online environment, you need to set the domain type to internal relay if the domain contains recipient addresses assigned to public folders. Directory-Based Edge Blocking cannot be used for public folders. 
```

2021-05-12 07:29 UTC, JohanFreelancer9 requested changes
Copy review - @FriedrichTobiasCC, please commit my suggested changes. Many thanks.

2021-05-12 08:40 UTC, JohanFreelancer9 approved these changes
@FriedrichTobiasCC - thank you.

2021-05-17 18:06 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-18 15:17 UTC, merged