fix Room and equipment mailboxes link
MicrosoftDocs/OfficeDocs-Exchange pull request #2612
Opened 2021-05-21 06:23 UTC by niclaszll

Adding a missing bracket.

2021-05-24 05:17 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-24 06:41 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/recipients/room-mailboxes.md
> +- If you're using room or equipment mailboxes in Microsoft 365 or Office 365, see [Room and equipment mailboxes](https://docs.microsoft.com/microsoft-365/admin/manage/room-and-equipment-mailboxes) fo
```suggestion
- If you're using room or equipment mailboxes in Microsoft 365 or Office 365, see [Room and equipment mailboxes](/microsoft-365/admin/manage/room-and-equipment-mailboxes) for more information.
```

2021-05-24 06:42 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/recipients/room-mailboxes.md
>  > If you're running Exchange 2013 in a hybrid scenario, make sure you create the room mailboxes in the appropriate place. Create your room mailboxes for your on-premises organization on-premises, and
```suggestion
> If you're running Exchange 2013 in a hybrid scenario, make sure you create the room mailboxes in the appropriate place. Create your room mailboxes for your on-premises organization on-premises, and room mailboxes for Exchange Online should be created in the cloud.
> Having problems? Ask for help in the Exchange forums. Visit the forums at: [Exchange Server](https://social.technet.microsoft.com/forums/office/home?category=exchangeserver), [Exchange Online](/answers/topics/office-exchange-server-itpro.html), or [Exchange Online Protection](https://social.technet.microsoft.com/forums/forefront/home?forum=FOPE).
```

2021-05-24 06:44 UTC, JohanFreelancer9 requested changes
Copy review. @niclaszll, could you please also commit my additional suggested changes? Many thanks.

2021-05-24 09:09 UTC, niclaszll commented
Added your suggested changes @JohanFreelancer9, thanks.

2021-05-24 10:48 UTC, JohanFreelancer9 approved these changes

2021-05-25 17:42 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-25 18:22 UTC, merged