adding delist portal link
MicrosoftDocs/OfficeDocs-Exchange pull request #2620
Opened 2021-05-26 13:13 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2530

2021-05-28 21:11 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-29 05:16 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-7-1-in-exchange-online.md
> +To remove the restriction on the sender's source email system, forward the NDR message to delist@messaging.microsoft.com and please also see [Use the delist portal to remove yourself from the blocked
```suggestion
To remove the restriction on the sender's source email system, forward the NDR message to delist@messaging.microsoft.com. Also see [Use the delist portal to remove yourself from the blocked senders list](/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis).
```

2021-05-29 05:20 UTC, JohanFreelancer9 requested changes
Copy review. For information, in accordance with the Microsoft Style Guide, we should not use the word "please" unless the customer is asked to do something that is inconvenient or the application or site is to blame for the situation. Many thanks.

2021-05-31 11:20 UTC, get-itips commented
> Copy review. For information, in accordance with the Microsoft Style Guide, we should not use the word "please" unless the customer is asked to do something that is inconvenient or the application or site is to blame for the situation. Many thanks.

good to know!

2021-05-31 15:58 UTC, JohanFreelancer9 approved these changes

2021-05-31 21:20 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-01 14:58 UTC, merged

2021-06-01 15:21 UTC, spp2 commented
Hi, 
please note that the added URL is incomplete, giving an error 404; 
and that the address delist@messaging.microsoft.com is still "blocked by an administrator on frondbridge.com", rendering this step useless .
It includes this text:

> NOTE: For issues sending to Office 365, please include an NDR or bounce message. https://aka.ms/o365snds

I see no point in keeping delist@messaging.microsoft.com in this help page.

2021-06-01 16:00 UTC, get-itips commented
> Hi,
> please note that the added URL is incomplete, giving an error 404;

the URL will not work in the PR but in the published version of the article (it will take time to sync)

> and that the address [delist@messaging.microsoft.com](mailto:delist@messaging.microsoft.com) is still "blocked by an administrator on frondbridge.com", rendering this step useless .

thanks for including this info.

2021-06-02 07:18 UTC, spp2 commented
> the URL will not work in the PR but in the published version of the article (it will take time to sync)

OK confirmed, thanks: 
I was concerned by the seemingly truncated URL, but it is correct actually.