Multiple changes
MicrosoftDocs/OfficeDocs-Exchange pull request #2637
Opened 2021-06-09 12:00 UTC by Batre-MSFT

Submitted new location of source side validation script, and couple other changes

2021-06-09 20:56 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-10 04:41 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md
> +The PF mailbox GUID mentioned in prvious command must be obtained from On-Premises server, if it is obtained from Exchange Online, the migration batch will fail with error "Cannot find a recipient th
```suggestion
The public folder mailbox GUID mentioned in the previous command must be obtained from the on-premises server; if it is obtained from Exchange Online, the migration batch will fail with the error "Cannot find a recipient that has mailbox GUID".
```

2021-06-10 04:45 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-17 04:08 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-17 15:30 UTC, merged