Exmaples were flipped
MicrosoftDocs/OfficeDocs-Exchange pull request #2641
Opened 2021-06-11 13:40 UTC by AvrumFeldman

I didn't test if my changes are correct per se. I just fixed the examples to match their notation.

2021-06-17 04:10 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-17 05:53 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/policy-and-compliance/ediscovery/message-properties-and-search-operators.md
>  - When searching a property, use double quotation marks (" ") if the search value consists of multiple words. For example **subject:budget Q1** returns messages that contain **budget** in the in the
```suggestion
- When searching a property, use double quotation marks (" ") if the search value consists of multiple words. For example **subject:budget Q1** returns messages that contain **budget** in the subject line and that contain **Q1** anywhere in the message or in any of the message properties. Using **subject:"budget Q1"** returns all messages that contain **budget Q1** anywhere in the subject line.
```

2021-06-17 05:55 UTC, JohanFreelancer9 requested changes
Copy review - @AvrumFeldman, not related to this PR but please commit the additional typo correction. Many thanks.

2021-06-21 05:43 UTC, JohanFreelancer9 approved these changes

2021-06-28 21:47 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-28 21:55 UTC, merged