Update manage-dynamic-distribution-groups.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2644
Opened 2021-06-11 18:24 UTC by JCrosbyMSFT

Added warning that DDLs are not synced back from EXO to Azure/Onprem

2021-06-16 01:26 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-22 15:24 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-23 06:50 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/manage-dynamic-distribution-groups.md
> +> Dynamic distribution groups are not synced from Exchange Online to Azure Active Directory or to your onpremises Active Directory. Therefore features such as Azure Conditional Access does not suppor
```suggestion
> - A dynamic distribution group includes any recipient in Active Directory with attribute values that match its filter. If a recipient's properties are modified to match the filter, the recipient could inadvertently become a group member and start receiving messages that are sent to the group. Well-defined, consistent account provisioning processes will reduce the chances of this issue occurring.
> - Dynamic distribution groups are not synced from Exchange Online to Azure Active Directory or to your on-premises Active Directory. Therefore, features such as Azure Conditional Access do not support being scoped to an Exchange Online dynamic distribution group.
```

2021-06-23 06:56 UTC, JohanFreelancer9 requested changes
Copy review. @JCrosbyMSFT - kindly commit my suggested changes if you agree with them.

2021-06-23 14:58 UTC, JohanFreelancer9 approved these changes

2021-06-24 18:12 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-24 19:04 UTC, merged