Update fix-issues-with-printers-scanners-and-lob-applications-that-se…
MicrosoftDocs/OfficeDocs-Exchange pull request #2648
Opened 2021-06-15 22:20 UTC by arindamthokder

…nd-email-using-off.md

2021-06-16 01:26 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-16 06:25 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +If you are getting one of the following erros-
```suggestion
If you are getting one of the following errors: 
```

2021-06-16 06:25 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +535 5.7.3 Authentication unsuccessful
```suggestion
- 535 5.7.3 Authentication unsuccessful
```

2021-06-16 06:25 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +5.7.57 Client not authenticated to send mail
```suggestion
- 5.7.57 Client not authenticated to send mail
```

2021-06-16 06:26 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +   From Microsoft 365 Admin Center, go to Active Users and select the user
```suggestion
   From Microsoft 365 Admin Center, go to Active Users and select the user.
```

2021-06-16 06:26 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +   Go to Mail tab
```suggestion
   Go to the Mail tab.
```

2021-06-16 06:27 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +   In the “Email apps” section, click on “Manage email apps”
```suggestion
   In the “Email apps” section, select **Manage email apps**.
```

2021-06-16 06:28 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +   Verify the “Authenticated SMTP” setting is checked (enabled)
```suggestion
   Verify that the “Authenticated SMTP” setting is checked (enabled).
```

2021-06-16 06:28 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +   Click Save changes.
```suggestion
   Select **Save changes**.
```

2021-06-16 06:31 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +2. Disable Multi Factor Authentication (MFA) on the licensed mailbox being used:
```suggestion
2. Disable Multi-Factor Authentication (MFA) on the licensed mailbox being used:
```

2021-06-16 06:33 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +   On the multi-factor authentication page, select the user and disable the Multi-Factor auth status.
```suggestion
   - In the Microsoft 365 admin center, in the left navigation menu, choose **Users** > **Active users**.
   - On the Active users page, choose **Multi-Factor Authentication**.
   - On the Multi-Factor Authentication page, select the user and disable the Multi-Factor Authentication status.
```

2021-06-16 06:35 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +3. Disable the [Azure Security Defaults](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults) by toggling the “Enable Security Defaults” to “No
```suggestion
3. Disable the [Azure Security Defaults](/azure/active-directory/fundamentals/concept-fundamentals-security-defaults) by toggling the **Enable Security Defaults** to **No**:
```

2021-06-16 06:37 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +   Select Save.
```suggestion
   - Sign in to the Azure portal as a Security administrator, Conditional Access administrator, or Global administrator.
   - Browse to Azure Active Directory > Properties.
   - Select **Manage security defaults**.
   - Set the **Enable security defaults** toggle to **No**.
   - Select **Save**.
```

2021-06-16 06:53 UTC, JohanFreelancer9 requested changes
Copy review - @arindamthokder, kindly commit my suggested changes. Many thanks.

2021-06-16 13:28 UTC, arindamthokder commented
> Copy review - @arindamthokder, kindly commit my suggested changes. Many thanks.

Suggested changes committed. Thanks a lot.

2021-06-17 04:09 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-17 06:15 UTC, JohanFreelancer9 approved these changes

2021-06-17 16:03 UTC, merged