SMTP Client authentication error: Add 4th solution
MicrosoftDocs/OfficeDocs-Exchange pull request #2707
Opened 2021-07-23 12:05 UTC by gcaringal

I came across following error when trying to send an email via SMTP: "5.7.57 Client not authenticated to send mail"
None of the 3 currently listed options worked. There is no mention in the article regarding a Conditional Access policy blocking legacy authentication.

I therefore propose to add a 4th option which is what helped me fix the error.

2021-07-24 00:39 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-24 04:22 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md
> +      - Select **Save**
```suggestion
      - Browse to **Azure Active Directory** > **Security** > **Conditional Access**.

      - In the policy that blocks Legacy Authentication, exclude the mailbox being used under **Users and Groups** > **Exclude**.

      - Select **Save**.
```

2021-07-24 04:24 UTC, JohanFreelancer9 requested changes
Copy review - @gcaringal, kindly commit the minor suggested changes. Many thanks.

2021-07-26 07:46 UTC, gcaringal commented
Thanks for the copy review @JohanFreelancer9.

2021-07-26 08:29 UTC, JohanFreelancer9 approved these changes

2021-07-27 16:45 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-07-27 21:11 UTC, merged