Updated
MicrosoftDocs/OfficeDocs-Exchange pull request #2709
Opened 2021-07-27 09:05 UTC by Batre-MSFT

Added scenario to address credential prompt issue

2021-07-27 16:45 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-28 08:45 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +This topic describes how to configure EXO mailboxes to access public folders at On-Premises. The topic also describes how to synchronize mail-enabled public folders if your users are in Microsoft 365
```suggestion
This topic describes how to configure EXO mailboxes to access on-premises public folders. The topic also describes how to synchronize mail-enabled public folders if your users are in Microsoft 365 or Office 365 and your Exchange Server 2010 SP3 public folders are on-premises. However, a Microsoft 365 or Office 365 user who is not represented by a MailUser object on-premises (local to the target public folder hierarchy) won't be able to access legacy or modern on-premises public folders.
```

2021-07-28 08:46 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +> The `Sync-MailPublicFolders.ps1` does not support modern authentication and works only with basic authentication. You must use an EXO account that supports basic authentication.
```suggestion
> The `Sync-MailPublicFolders.ps1` does not support modern authentication and works only with basic authentication. You must use an Exchange Online account that supports basic authentication.
```

2021-07-28 08:48 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +## Step 3: Download the script to synchronize mail enabled public folders
```suggestion
## Step 3: Download the script to synchronize mail-enabled public folders
```

2021-07-28 08:49 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +2. Save the files to Exchange On-Prmises server on which you'll be running the script. For example, C:\PFScripts.
```suggestion
2. Save the files to the Exchange on-premises server on which you'll be running the script. For example, C:\PFScripts.
```

2021-07-28 08:50 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +> The `Sync-MailPublicFolders.ps1` does not support modern authentication and works only with basic authentication. You must use an EXO account that supports basic authentication.
```suggestion
> `Sync-MailPublicFolders.ps1` does not support modern authentication and works only with basic authentication. You must use an Exchange Online account that supports basic authentication.
```

2021-07-28 08:52 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +A Microsoft 365 or Office 365 mailbox who is not represented by a MailUser object on-premises (local to the target public folder hierarchy) won't be able to access on-premises public folders.
```suggestion
A Microsoft 365 or Office 365 mailbox that is not represented by a MailUser object on-premises (local to the target public folder hierarchy) won't be able to access on-premises public folders.  
```

2021-07-28 08:53 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +You can use following command to identify such mailboxes:
```suggestion
You can use the following command to identify such mailboxes:
```

2021-07-28 08:54 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +The above users will keep getting credential prompt after public folder mailboox access is configured. Use one of the following solution for such users, before enabling public folder access:
```suggestion
These users will keep getting credential prompts after public folder mailbox access is configured. Use one of the following solutions for such users before enabling public folder access:
```

2021-07-28 08:58 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +1) Link the EXO only mailboxes, listed in step above, to On-Premises users by using the Knowledge Base article [Exchange Online users can't access legacy on-premises public folders](https://support.m
```suggestion
1. Link only the Exchange Online mailboxes listed in the previous step to on-premises users as described in [Exchange Online users can't access legacy on-premises public folders](https://support.microsoft.com/help/3106618).
```

2021-07-28 09:00 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +2) Use steps provided in [Controlled Connections to Public Folders](https://aka.ms/ControlPF) to enable public folder access only to mailboxes that have linked users at On-Premises.
```suggestion
2. Use the steps provided in [Controlled Connections to Public Folders](https://aka.ms/ControlPF) to enable public folder access only to mailboxes that have linked users on-premises.
```

2021-07-28 09:10 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-28 11:12 UTC, JohanFreelancer9 reviewed
@Batre-MSFT - please also commit the minor suggested change to line 159. Thanks.

2021-07-28 12:25 UTC, Batre-MSFT commented
> @Batre-MSFT - please also commit the minor suggested change to line 159. Thanks.

I hope all changes are committed now

2021-07-28 13:16 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-legacy-hybrid-public-folders.md
> +This topic describes how to configure EXO mailboxes to access on-premises public folders. The topic also describes how to synchronize mail-enabled public folders if your users are in Microsoft 365 or
```suggestion
This topic describes how to configure Exchange Online mailboxes to access on-premises public folders. The topic also describes how to synchronize mail-enabled public folders if your users are in Microsoft 365 or Office 365 and your Exchange Server 2010 SP3 public folders are on-premises. However, a Microsoft 365 or Office 365 user who is not represented by a MailUser object on-premises (local to the target public folder hierarchy) won't be able to access legacy or modern on-premises public folders.
```

2021-07-28 13:18 UTC, JohanFreelancer9 requested changes
@Batre-MSFT - my apologies, please also commit this change that I have missed. Many thanks for committing all the others. Looks good.

2021-07-28 13:22 UTC, JohanFreelancer9 approved these changes
Thank you @Batre-MSFT.

2021-07-30 03:16 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-07-30 15:21 UTC, merged