credential prompt
MicrosoftDocs/OfficeDocs-Exchange pull request #2710
Opened 2021-07-27 09:09 UTC by Batre-MSFT

Added steps to address credential prompt issue

2021-07-27 16:45 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-28 09:11 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md
> +A Microsoft 365 or Office 365 mailbox who is not represented by a MailUser object on-premises (local to the target public folder hierarchy) won't be able to access on-premises public folders.
```suggestion
A Microsoft 365 or Office 365 mailbox that is not represented by a MailUser object on-premises (local to the target public folder hierarchy) won't be able to access on-premises public folders.  
```

2021-07-28 09:12 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md
> +The above users will keep getting credential prompt after public folder mailboox access is configured. Use one of the following solution for such users, before enabling public folder access:
```suggestion
These users will keep getting credential prompts after public folder mailbox access is configured. Use one of the following solutions for such users before enabling public folder access:
```

2021-07-28 09:14 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md
> +1) Link the EXO only mailboxes, listed in step above, to On-Premises users by using the Knowledge Base article [Exchange Online users can't access legacy on-premises public folders](https://support.m
```suggestion
1. Link the Exchange Online only mailboxes listed in the previous step to on-premises users by using the steps described in [Exchange Online users can't access legacy on-premises public folders](https://support.microsoft.com/help/3106618).
```

2021-07-28 09:16 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md
> +2) Use steps provided in [Controlled Connections to Public Folders](https://aka.ms/ControlPF) to enable public folder access only to mailboxes that have linked users at On-Premises.
```suggestion
2. Use the steps provided in [Controlled Connections to Public Folders](https://aka.ms/ControlPF) to enable public folder access only to mailboxes that have linked users on-premises.
```

2021-07-28 09:17 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md
> +
```suggestion
```

2021-07-28 09:17 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-28 11:28 UTC, JohanFreelancer9 reviewed
@Batre-MSFT - Please also commit the changes to lines 96, 106, 108, and 109. Thanks.

2021-07-28 13:21 UTC, JohanFreelancer9 approved these changes
Thank you.

2021-07-30 03:16 UTC, scanum commented
@Kateyanne PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-07-30 15:14 UTC, merged