fixed a typo
MicrosoftDocs/OfficeDocs-Exchange pull request #2724
Opened 2021-08-09 08:10 UTC by jurajsucik

2021-08-09 19:52 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-10 06:11 UTC, JohanFreelancer9 requested changes
Copy review - @jurajsucik, kindly commit the suggested changes. Many thanks.

2021-08-10 06:11 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md
> +> If you need to unsubscribe from an email list subscription service, some subscription services require that use the original email address that you subscribed with. You can't unsubscribe by sending
```suggestion
> If you need to unsubscribe from an email list subscription service, some subscription services require that you use the original email address that you subscribed with. You can't unsubscribe by sending an email from a plus address.
```

2021-08-11 14:10 UTC, jurajsucik commented on Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md
> +> If you need to unsubscribe from an email list subscription service, some subscription services require that use the original email address that you subscribed with. You can't unsubscribe by sending
suggestion committed

2021-08-11 15:36 UTC, JohanFreelancer9 approved these changes

2021-08-13 09:48 UTC, jurajsucik commented
can this PR be merged now?

2021-08-13 18:09 UTC, merged