Update decommission-on-premises-exchange.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2742
Opened 2021-08-23 18:42 UTC by atguilmette

Updated scenario 3. It's important to continually remind admins that as long as directory synchronization is in use, at least one Exchange server will be required. We did not explicitly identify this requirement in scenario 3, implying that if they don't need public folders or SMTP relay, they can decom all servers.

2021-08-23 20:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-24 03:45 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/decommission-on-premises-exchange.md
> +**Solution**: We recommend against removing Exchange and the hybrid configuration at this point. If you were to even start the process by pointing the Autodiscover Records to Exchange Online, you wou
```suggestion
**Solution**: We recommend against removing Exchange and the hybrid configuration at this point. If you were to even start the process by pointing the Autodiscover Records to Exchange Online, you would immediately break some features like hybrid public folder access. You could change the MX record to point to Exchange Online Protection if it is not already, you could even remove some of the on-premises Exchange servers. However, you would need to keep enough in place to handle the remaining hybrid functions. Usually, this would lead to a very small on-premises footprint. Exchange-only services and features, such as public folders, will require you to either maintain your on-premises Exchange servers or migrate those services to Exchange Online.  Per scenarios one and two, if you maintain identity synchronization from Active Directory, you will need to continue to maintain at least one Exchange server on-premises.
```

2021-08-24 03:46 UTC, JohanFreelancer9 requested changes
Copy review - @atguilmette, kindly commit the minor suggested changes if you agree with them. Many thanks.

2021-08-24 14:57 UTC, JohanFreelancer9 approved these changes

2021-08-24 22:55 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-25 00:24 UTC, merged