Update renew-the-federation-certificate-exchange-2013-help.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2766
Opened 2021-09-03 06:52 UTC by andreig2735

The fact that the old expired certificate is still referenced in the federation trust object is causing confusion among exchange administrators since they want to remove the expired certificate. This issue is also a call generator in CSS.

For more clarity please see this issue:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1711 

and the blog post comments here by Mirela_Buru 

https://techcommunity.microsoft.com/t5/exchange-team-blog/keep-your-federation-trust-up-to-date/ba-p/2088788

2021-09-03 22:32 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-09-04 08:06 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md
> +**Note:** by design, after renewing the certificate, the expired certificate associated with the Federation trust cannot be removed from the Federation trust object.
```suggestion
    > [NOTE]
    > By design, after renewing the certificate, the expired certificate associated with the federation trust cannot be removed from the federation trust object. 
```

2021-09-04 08:09 UTC, JohanFreelancer9 requested changes
Copy review - @andreig2735, kindly commit the suggested change. Many thanks.

2021-09-07 10:59 UTC, JohanFreelancer9 approved these changes

2021-09-09 08:57 UTC, andreig2735 commented
Is there anything else needed ? I still can't see the approved changes in the public article. Thanks

2021-09-10 15:47 UTC, merged