Update run-a-message-trace-and-view-results.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2852
Opened 2021-11-08 19:07 UTC by kellybos

Updated information about DLP rule and sensitivity label events. These are now separate and it's important to make clear why type of sensitivity label events are included. These are EXO events only so are not included in the Exchange server location that is linked to later in the article.

2021-11-09 04:08 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-09 07:24 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md
> +  - **Sensitivity label:** A server side labeling event occurred. For example, a label automatically added to a message that includes an action to encrypt or added via the web or mobile client. This
```suggestion
  - **Sensitivity label:** A server-side labeling event occurred, such as a label automatically added to a message that includes an action to encrypt or added via the web or mobile client. This action is completed by the Exchange server and logged. A label added via Outlook will not be included in the event field.
```

2021-11-09 07:26 UTC, JohanFreelancer9 requested changes
Copy review - @kellybos, kindly commit the suggested changes if you agree with them. Many thanks.

2021-11-10 04:27 UTC, JohanFreelancer9 approved these changes

2021-11-10 05:14 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-11-10 17:44 UTC, tiburd commented
@JoanneHendrickson @chrisda 
Can you review?
Thanks!

2021-11-10 18:21 UTC, merged