Add classic EAC deprecation note to remote-wipe-on-mobile-phone.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2854
Opened 2021-11-08 22:19 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2850.

2021-11-09 04:08 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-09 07:44 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mobile-access/remote-wipe-on-mobile-phone.md
> +> This setting is not available on the new EAC. If the classic EAC was deprecated, you must use [Exchange Online PowerShell](#use-exchange-online-powershell-to-wipe-a-users-phone).
```suggestion
> This setting is not available in the new EAC. If the classic EAC was deprecated, you must use [Exchange Online PowerShell](#use-exchange-online-powershell-to-wipe-a-users-phone).
```

2021-11-09 07:45 UTC, JohanFreelancer9 requested changes
Copy review - minor suggestion.

2021-11-09 08:53 UTC, JohanFreelancer9 approved these changes

2021-11-10 05:14 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-11-10 17:45 UTC, merged