Add EAC steps to plus-addressing-in-exchange-online.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2941
Opened 2022-01-14 08:53 UTC by dariomws

Closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2927.

2022-01-17 06:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-17 08:39 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md
> +2. Select **Turn on plus addressing for your organization** and then click **Save**.
```suggestion
1. In the new [Exchange admin center](https://admin.exchange.microsoft.com), go to **Settings** \> **Mail flow**.

2. Select **Turn on plus addressing for your organization** and then select **Save**.
```

2022-01-17 08:39 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-17 08:42 UTC, dariomws commented on Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md
> +2. Select **Turn on plus addressing for your organization** and then click **Save**.
Let's keep "click" as it's a button.

2022-01-17 08:45 UTC, JohanFreelancer9 approved these changes

2022-01-19 13:44 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-01-19 21:52 UTC, tiburd commented on Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md
> +2. Select **Turn on plus addressing for your organization** and then click **Save**.
```suggestion
2. Select **Turn on plus addressing for your organization**, and then select **Save**.
```

2022-01-19 21:57 UTC, tiburd commented on Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md
> +2. Select **Turn on plus addressing for your organization** and then click **Save**.
It's Microsoft style to use "select" for buttons:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/54688693/150220538-34ac700c-02ad-44be-bec7-22498f823974.png">

2022-01-19 22:02 UTC, merged