Update updates.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2951
Opened 2022-01-19 23:15 UTC by MarcoFrancisco

The link "Cumulative Update 11 for Exchange Server 2019" directs to Exchange 2016 CU22

2022-01-22 00:45 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-22 05:08 UTC, JohanFreelancer9 requested changes
Copy review - @MarcoFrancisco, kindly commit the suggested change to remove the locale from the link. Many thanks.

2022-01-23 06:37 UTC, JohanFreelancer9 approved these changes

2022-01-26 20:28 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-01-26 22:26 UTC, merged