improve note
MicrosoftDocs/OfficeDocs-Exchange pull request #2960
Opened 2022-01-25 13:51 UTC by get-itips

@dariomws thoughts?

closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2949

2022-01-25 15:50 UTC, dariomws approved these changes

2022-01-26 20:27 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-27 06:54 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md
> +> Before running the script, we recommend that you first simulate the actions that the script would take in your environment by running it as described above with the `-WhatIf` switch. As part of the
```suggestion
> Before running the script, we recommend that you first simulate the actions that the script would take in your environment by running it as described above with the `-WhatIf` switch. As part of the sync operation, the script, when appropriate, could create, update, or delete mail-enabled public folder objects on Exchange Online.
```

2022-01-27 06:54 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-28 05:45 UTC, JohanFreelancer9 approved these changes

2022-01-30 22:46 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-01-31 20:08 UTC, merged