Minor text mistakes
MicrosoftDocs/OfficeDocs-Exchange pull request #2975
Opened 2022-02-04 12:48 UTC by YuriySamorodov

2022-02-07 01:09 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-02-12 00:19 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-02-14 22:59 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-02-15 07:35 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/perform-gspace-migration-powershell.md
> +- How the migration happens in backend, see [Overview of the process](how-it-all-works-in-the-backend.md)
```suggestion
- Completion of migration batch, see [Completion of migration batch in PowerShell](completion-gspae-migration-batch-powershell.md)
- How the migration happens in the backend, see [Overview of the process](how-it-all-works-in-the-backend.md)
```

2022-02-15 07:36 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/perform-gspace-migration-powershell.md
> +- How the migration happens in backend, see [Overview of the process](how-it-all-works-in-the-backend.md)
```suggestion
- How the migration happens in the backend, see [Overview of the process](how-it-all-works-in-the-backend.md)
```

2022-02-15 07:37 UTC, JohanFreelancer9 requested changes
Copy review - @YuriySamorodov, kindly commit the minor additional suggested change. Many thanks.

2022-02-15 09:03 UTC, JohanFreelancer9 approved these changes

2022-02-15 23:52 UTC, JoanneHendrickson commented
@YuriySamorodov   Can you please select the checkbox on your branch "Allow edits from maintainers" otherwise I cannot merge this PR.

2022-02-16 07:48 UTC, YuriySamorodov commented
> @YuriySamorodov Can you please select the checkbox on your branch "Allow edits from maintainers" otherwise edit or merge this PR. thanks

Sorry about that. This is completed

2022-02-21 23:12 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-02-22 21:17 UTC, merged