Update architecture.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2986
Opened 2022-02-12 18:39 UTC by elctrogamr1

Minor grammatical fixes.

2022-02-14 22:59 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-02-24 02:56 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/architecture/architecture.md
> +Exchange uses a single building block architecture that provides email services for deployments at all sizes, from small organizations to the largest multi-national corporations. This architecture is
```suggestion
Exchange uses a single building block architecture that provides email services for deployments of all sizes, from small organizations to the largest multi-national corporations. This architecture is described in the following diagram.
```

2022-02-24 02:57 UTC, JohanFreelancer9 requested changes
Copy review - @elctrogamr1, kindly commit the additional suggested change. Many thanks.

2022-03-04 02:07 UTC, elctrogamr1 commented
Hi @JohanFreelancer9, I committed the additional change. By the way, this is my first PR ever, so please let me know if I missed anything. Thank you for the suggested change, too!

2022-03-04 03:45 UTC, JohanFreelancer9 approved these changes

2022-03-05 12:42 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-07 18:42 UTC, merged