Update antimalware-procedures.md
MicrosoftDocs/OfficeDocs-Exchange pull request #2994
Opened 2022-02-19 00:44 UTC by MarcoLFrancisco

Feel free to propose any changes to the description. At first view from the available anti Malware articles it seems it is not possible to bypass anti-Malware detection for a user subgroup without disabling the detection for all recipients. Maybe the bypass part of this article can have this alternative method described and referenced in the part I edited. Or I can create a new article for this particular scenario.

2022-02-21 23:11 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-02-23 22:59 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-03-01 04:50 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/antimalware-procedures.md
> +- Configure a Malware Filtering  Bypass for a Recipient or Group of Recipients
```suggestion
- Configure a malware filtering  bypass for a recipient or group of recipients
```

2022-03-01 04:52 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/antimalware-procedures.md
> +## Configure a Malware Filter Bypass for a recipient or Group of Recipients
```suggestion
## Configure a malware filtering bypass for a recipient or group of recipients
```

2022-03-01 04:55 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/antimalware-procedures.md
> +To allow for a particular recipient or group of recipents to recieve emails with attachments that would otherwise be detected and thus deleted by the default anti-Malware Policy, a new anti-Malware P
```suggestion
To allow for a particular recipient or group of recipients to receive emails with attachments that would otherwise be detected and thus deleted by the default anti-malware policy, a new anti-malware policy has to be created, either using EAC or PowerShell. This policy should be set to scan emails for all recipients and an exclusion condition must be set within that policy for the recipient or group that is intended to receive such content.
```

2022-03-01 04:58 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/antimalware-procedures.md
> +Using EAC to Creeate the new anti-Malware Policy:
```suggestion
Using EAC to create the new anti-malware policy:
```

2022-03-01 05:00 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/antimalware-procedures.md
> +This will create a Malware Policy that will scan all email traffic exepct messages sent to the excempt user or group.
```suggestion
This will create a malware policy that will scan all email traffic except messages sent to the exempt user or group.
```

2022-03-01 05:01 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/antimalware-procedures.md
> +Using Exchange Management Shell to create an anti-Malware Policy:
```suggestion
Using Exchange Management Shell to create an anti-malware policy:
```

2022-03-01 05:09 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/antimalware-procedures.md
> +[Use the Exchange Management Shell to modify a malware filter rule](/Exchange/antispam-and-antimalware/antimalware-protection/antimalware-procedures?view=exchserver-2019#use-the-exchange-management-s
```suggestion
[Use the Exchange Management Shell to modify a malware filtering rule](/Exchange/antispam-and-antimalware/antimalware-protection/antimalware-procedures?view=exchserver-2019#use-the-exchange-management-shell-to-create-antimalware-policies).
```

2022-03-01 05:10 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/antimalware-procedures.md
> +https://docs.microsoft.com/en-us/Exchange/antispam-and-antimalware/antimalware-protection/antimalware-procedures?view=exchserver-2019#use-the-exchange-management-shell-to-create-antimalware-policies
```suggestion
```

2022-03-01 05:15 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/antimalware-procedures.md
> +After creating the anti-Malware policy and setting the apropriate exclusion, a new anti-Malware policy has to be created in order for the unscaned messages to bypass the default anti-Malware Policy t
```suggestion
After creating the anti-malware policy and setting the appropriate exclusion, a new anti-malware policy has to be created in order for the unscanned messages to bypass the default anti-malware policy that always has the lowest priority. This change can be achieved by using Exchange Management Shell to set the value of the parameter "-BypassInboundMessages" of this anti-malware filtering rule to True. For detailed syntax and parameter information, see [Set-MalwareFilterPolicy](/powershell/module/exchange/set-malwarefilterpolicy?view=exchange-ps).
```

2022-03-01 05:21 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/antimalware-procedures.md
> +This method does not require service restart and can allow for Exchange Administrators and Security teams to temporarly or permanently bypass anti-Malware detection for a particular recipient or grou
```suggestion
This method does not require a service restart and can allow for Exchange administrators and security teams to temporarily or permanently bypass anti-malware detection for a particular recipient or group, thus having otherwise undeliverable messages delivered to that particular subgroup without compromising the security of the entire Exchange organization and ultimately retaining security within their systems and for their clients.  
```

2022-03-01 05:22 UTC, JohanFreelancer9 requested changes
Copy review - @MarcoLFrancisco, kindly commit the suggested changes. Many thanks.

2022-03-01 07:14 UTC, MarcoLFrancisco commented
> Copy review - @MarcoLFrancisco, kindly commit the suggested changes. Many thanks.

Done. Thank you, great work.

2022-03-01 10:40 UTC, JohanFreelancer9 approved these changes

2022-03-05 12:42 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-07 19:02 UTC, merged