fix acronym
MicrosoftDocs/OfficeDocs-Exchange pull request #3100
Opened 2022-04-29 13:50 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/3087

2022-05-02 11:27 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/manage-hybrid-exchange-recipients-with-management-tools.md
> +In Exchange Hybrid environments, you must have an active Exchange Server to manage recipients attributes. First, attributes are edited using an Exchange Server in on-premises Active Directory (AD), t
```suggestion
In Exchange Hybrid environments, you must have an active Exchange Server to manage recipients' attributes. First, attributes are edited using an Exchange Server in on-premises Azure Active Directory (Azure AD), which are then copied to Azure AD using directory synchronization. On-premises recipients can’t be modified directly in Azure AD or Exchange Online. Therefore you have to keep an Exchange Server running using directory synchronization via the Azure AD Connect tool.
```

2022-05-02 11:31 UTC, JohanFreelancer9 requested changes
Copy review - @tips, just a few additional suggestions if you agree. In the first instance, we should include the acronym in parentheses following the spelled-out term. On subsequent mentions in the same article, we can use the acronym without spelling it out.

2022-05-03 04:29 UTC, JohanFreelancer9 approved these changes

2022-05-12 03:12 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-05-12 13:04 UTC, merged