update instructions
MicrosoftDocs/OfficeDocs-Exchange pull request #3114
Opened 2022-05-06 20:45 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/3049

2022-05-07 04:09 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/googleworkspace-migration-prerequisites.md
> +7. Click **Add Another Role**, type in "Create Service Accounts" into the Filter and select **Create Service Accounts**.
```suggestion
5. Select the appropriate resource and in the right-hand pane under the **Permissions** tab select **Add Principal**.
6. Enter your Google Migration admin login, enter *Project Creator* in the filter, and select **Project Creator**.
7. Select **Add Another Role**, enter *Create Service Accounts* in the filter, and select **Create Service Accounts**.
```

2022-05-07 04:09 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-09 04:47 UTC, JohanFreelancer9 approved these changes

2022-05-12 03:11 UTC, scanum commented
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-05-24 14:40 UTC, merged