Updated sentence for better readability.
MicrosoftDocs/OfficeDocs-Exchange pull request #3117
Opened 2022-05-10 00:39 UTC by lukemurraynz

Updated sentence for better readability. #ATCP

2022-05-16 14:18 UTC, johnynitro commented on Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md
> +2. You must use a certificate issued by a trusted certification authority (CA) with your Outlook Anywhere configuration in order for Microsoft 365 or Office 365 to run a cutover migration. If you are
If you are doing a cutover migration, you will **need** to add

2022-05-17 10:17 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md
> +2. You must use a certificate issued by a trusted certification authority (CA) with your Outlook Anywhere configuration in order for Microsoft 365 or Office 365 to run a cutover migration. If you are
```suggestion
2. You must use a certificate issued by a trusted certification authority (CA) with your Outlook Anywhere configuration in order for Microsoft 365 or Office 365 to run a cutover migration. If you are doing a cutover migration, you will need to add the Outlook Anywhere and Autodiscover services to your certificate. For instructions on how to set up certificates, see:
```

2022-05-17 10:18 UTC, JohanFreelancer9 requested changes
Copy review - @lukemurraynz, kindly commit the suggested change. Many thanks.

2022-05-17 19:31 UTC, lukemurraynz commented on Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md
> +2. You must use a certificate issued by a trusted certification authority (CA) with your Outlook Anywhere configuration in order for Microsoft 365 or Office 365 to run a cutover migration. If you are
Updated.

2022-05-18 04:16 UTC, JohanFreelancer9 approved these changes

2022-05-23 17:45 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-05-23 18:25 UTC, merged