Update block-legacy-auth-2019-hybrid.md
MicrosoftDocs/OfficeDocs-Exchange pull request #3119
Opened 2022-05-10 17:19 UTC by chrismcgurk

Adding information regarding migration endpoints

2022-05-24 05:13 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/hybrid-deployment/block-legacy-auth-2019-hybrid.md
> +Migration endpoints in Office 365 use Exchange Web Services (EWS) to connect to Exchange On-Premises to migrate mailboxes from On-Premises to Exchange Online. When setting up authentication policies,
```suggestion
Migration endpoints in Office 365 use Exchange Web Services (EWS) to connect to Exchange on-premises to migrate mailboxes from on-premises to Exchange Online. When setting up authentication policies, ensure that the accounts associated with migration endpoints are not part of a policy that has *BlockLegacyAuthWebServices* set to True. 
```

2022-05-24 05:14 UTC, JohanFreelancer9 requested changes
Copy review - @chrismcgurk, kindly commit the suggested changes. Many thanks.

2022-05-25 04:06 UTC, JohanFreelancer9 approved these changes

2022-06-06 02:45 UTC, scanum commented
@chrisda PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-06-06 16:45 UTC, merged