Update prepare-ad-and-domains.md
MicrosoftDocs/OfficeDocs-Exchange pull request #3125
Opened 2022-05-14 22:55 UTC by johnynitro

2022-05-16 05:11 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md
> +> If Exchange is deployed in a multi-site Active Directory environment and is not in the same site as the Domain Controller that holds the Schema Master role, you cannot prepare Active Directory usin
```suggestion
> If Exchange is deployed in a multi-site Active Directory environment and is not in the same site as the domain controller that holds the Schema Master role, you cannot prepare Active Directory using the wizard. Instead, follow Step 1 and Step 2 in this topic. 
```

2022-05-16 05:11 UTC, JohanFreelancer9 requested changes
Copy review - @johnynitro, kindly commit the minor suggested change. Many thanks.

2022-05-16 12:48 UTC, JohanFreelancer9 approved these changes

2022-05-23 17:47 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-05-23 18:26 UTC, merged