Update address-rewriting.md
MicrosoftDocs/OfficeDocs-Exchange pull request #3130
Opened 2022-05-17 08:36 UTC by MarcoLFrancisco

DKIM signing happens before address rewrite, meaning it cant be used if there is outbound rewrite.

2022-05-17 09:15 UTC, MarcoLFrancisco commented
DKIM signing happens before address rewrite, meaning it cant be used if there is outbound rewrite.

2022-05-19 08:11 UTC, JohanFreelancer9 commented on Exchange/ExchangeServer/architecture/edge-transport-servers/address-rewriting.md
> +> DKIM signing is not supported for outboud email messages using rewriten addresses as it happens before the address rewriting process. If your organization requires DKIM signing for outbound email,
```suggestion
> DKIM signing is not supported for outbound email messages using rewritten addresses as it happens before the address rewriting process. If your organization requires DKIM signing for outbound email, be aware that DKIM validation will fail after implementing address rewriting.
```

2022-05-19 08:13 UTC, JohanFreelancer9 requested changes
Copy review - @MarcoLFrancisco, kindly commit the suggested changes. Many thanks.

2022-05-19 08:35 UTC, JohanFreelancer9 approved these changes

2022-05-23 18:29 UTC, merged