Reference the other article in decommission-on-premises-exchange.md
MicrosoftDocs/OfficeDocs-Exchange pull request #3137
Opened 2022-05-20 12:53 UTC by dariomws

2022-05-21 07:24 UTC, JohanFreelancer9 commented on Exchange/ExchangeHybrid/decommission-on-premises-exchange.md
> +> Currently, if you keep an Exchange server running just for recipient management, you may be able to shut down your last Exchange server and manage recipients using Windows PowerShell. For more info
```suggestion
> Currently, if you keep an Exchange server running just for recipient management, you may be able to shut down your last Exchange server and manage recipients using Windows PowerShell. For more information, see [Manage recipients in Exchange Hybrid environments using Management tools](/exchange/manage-hybrid-exchange-recipients-with-management-tools).
```

2022-05-21 07:24 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-23 14:22 UTC, JohanFreelancer9 approved these changes

2022-05-23 17:48 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-05-23 18:30 UTC, merged