Correct permissions
MicrosoftDocs/OfficeDocs-Exchange pull request #3176
Opened 2022-06-10 16:50 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/3159

source https://techcommunity.microsoft.com/t5/exchange-team-blog/a-new-recoverableitems-experience-comes-to-exchange-online/ba-p/1505353

"Admins must manually add the Mailbox Import Export RBAC role to accounts they wish to use the Recover Deleted Items feature with."

and also tested, Discovery Management is not enough to see the recover deleted items option in the EAC and to use the cmdlets, removing also the link to an article that does not mention this.

2022-06-12 09:15 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages.md
> +You need _Mailbox Import Export_ RBAC role before you can do this procedure or procedures.
```suggestion
You need the _Mailbox Import Export_ RBAC role before you can do this procedure or procedures.
```

2022-06-12 09:15 UTC, JohanFreelancer9 commented on Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages.md
> +You need _Mailbox Import Export_ RBAC role before you can do this procedure or procedures.
```suggestion
You need the _Mailbox Import Export_ RBAC role before you can do this procedure or procedures.
```

2022-06-12 09:16 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-13 04:31 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-06-14 19:38 UTC, merged